#!/usr/bin/env python3
"""Disambiguate names a barrel re-exports from more than one module (FR-025).

`src/apis/index.ts` is a list of `export * from './XApi'`. An operation carrying two tags is
emitted into both tag modules, so `getUserScores`, tagged both `score` and `user`, produces an
identical `GetUserScoresRequest` in ScoreApi.ts and UserApi.ts. TypeScript refuses the ambiguity
with TS2308 and the whole build fails, which is what tsc suggests fixing by "explicitly
re-exporting": an explicit `export { Name } from './One'` wins over the star exports.

Only duplicates whose declarations are textually identical are disambiguated. Two different types
that happen to share a name are a real conflict, not an ambiguity, and picking one would silently
export the wrong type. Those are reported and left for tsc to fail on, where the error names the
line rather than pointing back here.

Idempotent: the generated block is delimited by markers and rebuilt from scratch on every run.
"""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
BARRELS = [ROOT / "src" / "apis" / "index.ts", ROOT / "src" / "models" / "index.ts"]

BEGIN = "// BEGIN generated by tools/patches/85_barrel_dedup.py"
END = "// END generated by tools/patches/85_barrel_dedup.py"

STAR = re.compile(r"^export \* from '\./([^']+?)(?:\.js)?';$", re.MULTILINE)
DECL = re.compile(
    r"^export\s+(?:declare\s+)?(?:interface|type|const|function|class|enum)\s+([A-Za-z_$][\w$]*)",
    re.MULTILINE,
)


def _declaration_text(text: str, start: int, limit: int) -> str:
    """The declaration itself, without the JSDoc block that introduces the next one.

    Slicing to the next `export` would carry that comment along, and it differs between modules
    purely because the declaration after it differs. Every duplicate would then look like a
    conflict. Balance braces from the first `{`, or stop at the first `;` for an alias.
    """
    segment = text[start:limit]
    brace = segment.find("{")
    semicolon = segment.find(";")
    if brace == -1 or (semicolon != -1 and semicolon < brace):
        return " ".join(segment[: semicolon + 1].split()) if semicolon != -1 else ""
    depth = 0
    for index in range(brace, len(segment)):
        if segment[index] == "{":
            depth += 1
        elif segment[index] == "}":
            depth -= 1
            if depth == 0:
                tail = segment[index + 1 :]
                extra = tail.find(";")
                end = index + 1 + (extra + 1 if extra != -1 and not tail[:extra].strip("\n ") else 0)
                return " ".join(segment[:end].split())
    return " ".join(segment.split())


def declarations(module: pathlib.Path) -> dict[str, str]:
    """Exported top-level name -> its declaration text, for comparing two modules' versions."""
    text = module.read_text()
    found: dict[str, str] = {}
    matches = list(DECL.finditer(text))
    for i, match in enumerate(matches):
        limit = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body = _declaration_text(text, match.start(), limit)
        # A name can be declared twice in one module (the `const` and the `type` of an enum pair).
        found[match.group(1)] = found.get(match.group(1), "") + body
    return found


def dedup(barrel: pathlib.Path) -> None:
    if not barrel.is_file():
        sys.exit(f"85_barrel_dedup: {barrel} is missing (FR-025)")

    text = barrel.read_text()
    body = text.split(BEGIN)[0].rstrip() + "\n"

    modules = STAR.findall(body)
    if not modules:
        sys.exit(f"85_barrel_dedup: no star exports in {barrel.name}, the layout changed (FR-025)")

    owners: dict[str, list[tuple[str, str]]] = {}
    for module in modules:
        path = barrel.parent / f"{module}.ts"
        if not path.is_file():
            continue
        for name, decl in declarations(path).items():
            owners.setdefault(name, []).append((module, decl))

    resolved: list[str] = []
    conflicts: list[str] = []
    for name, entries in sorted(owners.items()):
        if len(entries) < 2:
            continue
        if len({decl for _, decl in entries}) == 1:
            resolved.append(f"export {{ {name} }} from './{entries[0][0]}.js';")
        else:
            conflicts.append(f"{name}: {', '.join(module for module, _ in entries)}")

    if resolved:
        block = "\n".join(
            [
                "",
                BEGIN,
                "// Operations carrying two tags are emitted into both tag modules. These names are",
                "// identical in each, so one explicit re-export resolves the TS2308 ambiguity.",
                *resolved,
                END,
                "",
            ]
        )
        body = body.rstrip() + "\n" + block
    barrel.write_text(body)

    print(f"    barrel {barrel.parent.name}/index.ts: {len(resolved)} name(s) disambiguated")
    for conflict in conflicts:
        # Not an ambiguity: two different declarations share a name. tsc reports it precisely.
        print(f"    barrel {barrel.parent.name}/index.ts: CONFLICT, differing declarations: {conflict}")


for target in BARRELS:
    dedup(target)
