/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML or MIDI files * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and interoduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * OpenAPI spec version: 2.4.0
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AssignmentSubmission', 'model/GoogleClassroomCoursework', 'model/MediaAttachment'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AssignmentSubmission'), require('./GoogleClassroomCoursework'), require('./MediaAttachment'));
  } else {
    // Browser globals (root is window)
    if (!root.FlatApi) {
      root.FlatApi = {};
    }
    root.FlatApi.Assignment = factory(root.FlatApi.ApiClient, root.FlatApi.AssignmentSubmission, root.FlatApi.GoogleClassroomCoursework, root.FlatApi.MediaAttachment);
  }
}(this, function(ApiClient, AssignmentSubmission, GoogleClassroomCoursework, MediaAttachment) {
  'use strict';




  /**
   * The Assignment model module.
   * @module model/Assignment
   * @version 2.4.0
   */

  /**
   * Constructs a new <code>Assignment</code>.
   * Assignment details
   * @alias module:model/Assignment
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>Assignment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Assignment} obj Optional instance to populate.
   * @return {module:model/Assignment} The populated <code>Assignment</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('classroom')) {
        obj['classroom'] = ApiClient.convertToType(data['classroom'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('attachments')) {
        obj['attachments'] = ApiClient.convertToType(data['attachments'], [MediaAttachment]);
      }
      if (data.hasOwnProperty('submissions')) {
        obj['submissions'] = ApiClient.convertToType(data['submissions'], [AssignmentSubmission]);
      }
      if (data.hasOwnProperty('creator')) {
        obj['creator'] = ApiClient.convertToType(data['creator'], 'String');
      }
      if (data.hasOwnProperty('creationDate')) {
        obj['creationDate'] = ApiClient.convertToType(data['creationDate'], 'Date');
      }
      if (data.hasOwnProperty('scheduledDate')) {
        obj['scheduledDate'] = ApiClient.convertToType(data['scheduledDate'], 'Date');
      }
      if (data.hasOwnProperty('dueDate')) {
        obj['dueDate'] = ApiClient.convertToType(data['dueDate'], 'Date');
      }
      if (data.hasOwnProperty('googleClassroom')) {
        obj['googleClassroom'] = GoogleClassroomCoursework.constructFromObject(data['googleClassroom']);
      }
    }
    return obj;
  }

  /**
   * State of the assignment
   * @member {module:model/Assignment.StateEnum} state
   */
  exports.prototype['state'] = undefined;
  /**
   * Title of the assignment
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * The unique identifier of the class where this assignment was posted
   * @member {String} classroom
   */
  exports.prototype['classroom'] = undefined;
  /**
   * Description and content of the assignment
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {Array.<module:model/MediaAttachment>} attachments
   */
  exports.prototype['attachments'] = undefined;
  /**
   * @member {Array.<module:model/AssignmentSubmission>} submissions
   */
  exports.prototype['submissions'] = undefined;
  /**
   * The User unique identifier of the creator of this assignment 
   * @member {String} creator
   */
  exports.prototype['creator'] = undefined;
  /**
   * The creation date of this assignment
   * @member {Date} creationDate
   */
  exports.prototype['creationDate'] = undefined;
  /**
   * The publication (scheduled) date of the assignment. If this one is specified, the assignment will only be listed to the teachers of the class. 
   * @member {Date} scheduledDate
   */
  exports.prototype['scheduledDate'] = undefined;
  /**
   * The due date of this assignment, late submissions will be marked as paste due. 
   * @member {Date} dueDate
   */
  exports.prototype['dueDate'] = undefined;
  /**
   * @member {module:model/GoogleClassroomCoursework} googleClassroom
   */
  exports.prototype['googleClassroom'] = undefined;


  /**
   * Allowed values for the <code>state</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StateEnum = {
    /**
     * value: "draft"
     * @const
     */
    "draft": "draft",
    /**
     * value: "active"
     * @const
     */
    "active": "active",
    /**
     * value: "archived"
     * @const
     */
    "archived": "archived"  };


  return exports;
}));


