/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro (GP3, GP4, GP5, GPX, GP), PowerTab, TuxGuitar and MuseScore files * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and interoduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AssignmentSubmission from './AssignmentSubmission';
import GoogleClassroomCoursework from './GoogleClassroomCoursework';
import MediaAttachment from './MediaAttachment';

/**
 * The Assignment model module.
 * @module model/Assignment
 * @version 2.9.0
 */
class Assignment {
    /**
     * Constructs a new <code>Assignment</code>.
     * Assignment details
     * @alias module:model/Assignment
     */
    constructor() { 
        
        Assignment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Assignment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Assignment} obj Optional instance to populate.
     * @return {module:model/Assignment} The populated <code>Assignment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Assignment();

            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('classroom')) {
                obj['classroom'] = ApiClient.convertToType(data['classroom'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], [MediaAttachment]);
            }
            if (data.hasOwnProperty('submissions')) {
                obj['submissions'] = ApiClient.convertToType(data['submissions'], [AssignmentSubmission]);
            }
            if (data.hasOwnProperty('creator')) {
                obj['creator'] = ApiClient.convertToType(data['creator'], 'String');
            }
            if (data.hasOwnProperty('creationDate')) {
                obj['creationDate'] = ApiClient.convertToType(data['creationDate'], 'Date');
            }
            if (data.hasOwnProperty('scheduledDate')) {
                obj['scheduledDate'] = ApiClient.convertToType(data['scheduledDate'], 'Date');
            }
            if (data.hasOwnProperty('dueDate')) {
                obj['dueDate'] = ApiClient.convertToType(data['dueDate'], 'Date');
            }
            if (data.hasOwnProperty('googleClassroom')) {
                obj['googleClassroom'] = GoogleClassroomCoursework.constructFromObject(data['googleClassroom']);
            }
        }
        return obj;
    }


}

/**
 * State of the assignment
 * @member {module:model/Assignment.StateEnum} state
 */
Assignment.prototype['state'] = undefined;

/**
 * Title of the assignment
 * @member {String} title
 */
Assignment.prototype['title'] = undefined;

/**
 * The unique identifier of the class where this assignment was posted
 * @member {String} classroom
 */
Assignment.prototype['classroom'] = undefined;

/**
 * Description and content of the assignment
 * @member {String} description
 */
Assignment.prototype['description'] = undefined;

/**
 * @member {Array.<module:model/MediaAttachment>} attachments
 */
Assignment.prototype['attachments'] = undefined;

/**
 * @member {Array.<module:model/AssignmentSubmission>} submissions
 */
Assignment.prototype['submissions'] = undefined;

/**
 * The User unique identifier of the creator of this assignment 
 * @member {String} creator
 */
Assignment.prototype['creator'] = undefined;

/**
 * The creation date of this assignment
 * @member {Date} creationDate
 */
Assignment.prototype['creationDate'] = undefined;

/**
 * The publication (scheduled) date of the assignment. If this one is specified, the assignment will only be listed to the teachers of the class. 
 * @member {Date} scheduledDate
 */
Assignment.prototype['scheduledDate'] = undefined;

/**
 * The due date of this assignment, late submissions will be marked as paste due. 
 * @member {Date} dueDate
 */
Assignment.prototype['dueDate'] = undefined;

/**
 * @member {module:model/GoogleClassroomCoursework} googleClassroom
 */
Assignment.prototype['googleClassroom'] = undefined;





/**
 * Allowed values for the <code>state</code> property.
 * @enum {String}
 * @readonly
 */
Assignment['StateEnum'] = {

    /**
     * value: "draft"
     * @const
     */
    "draft": "draft",

    /**
     * value: "active"
     * @const
     */
    "active": "active",

    /**
     * value: "archived"
     * @const
     */
    "archived": "archived"
};



export default Assignment;

