/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML or MIDI files * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and interoduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * OpenAPI spec version: 2.2.0
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ClassDetailsCanvas', 'model/ClassDetailsGoogleClassroom', 'model/ClassDetailsGoogleDrive', 'model/ClassDetailsLti', 'model/ClassState', 'model/GroupDetails'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ClassDetailsCanvas'), require('./ClassDetailsGoogleClassroom'), require('./ClassDetailsGoogleDrive'), require('./ClassDetailsLti'), require('./ClassState'), require('./GroupDetails'));
  } else {
    // Browser globals (root is window)
    if (!root.FlatApi) {
      root.FlatApi = {};
    }
    root.FlatApi.ClassDetails = factory(root.FlatApi.ApiClient, root.FlatApi.ClassDetailsCanvas, root.FlatApi.ClassDetailsGoogleClassroom, root.FlatApi.ClassDetailsGoogleDrive, root.FlatApi.ClassDetailsLti, root.FlatApi.ClassState, root.FlatApi.GroupDetails);
  }
}(this, function(ApiClient, ClassDetailsCanvas, ClassDetailsGoogleClassroom, ClassDetailsGoogleDrive, ClassDetailsLti, ClassState, GroupDetails) {
  'use strict';




  /**
   * The ClassDetails model module.
   * @module model/ClassDetails
   * @version 2.2.0
   */

  /**
   * Constructs a new <code>ClassDetails</code>.
   * A classroom
   * @alias module:model/ClassDetails
   * @class
   */
  var exports = function() {
    var _this = this;


















  };

  /**
   * Constructs a <code>ClassDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClassDetails} obj Optional instance to populate.
   * @return {module:model/ClassDetails} The populated <code>ClassDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ClassState.constructFromObject(data['state']);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('section')) {
        obj['section'] = ApiClient.convertToType(data['section'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('organization')) {
        obj['organization'] = ApiClient.convertToType(data['organization'], 'String');
      }
      if (data.hasOwnProperty('owner')) {
        obj['owner'] = ApiClient.convertToType(data['owner'], 'String');
      }
      if (data.hasOwnProperty('creationDate')) {
        obj['creationDate'] = ApiClient.convertToType(data['creationDate'], 'Date');
      }
      if (data.hasOwnProperty('enrollmentCode')) {
        obj['enrollmentCode'] = ApiClient.convertToType(data['enrollmentCode'], 'String');
      }
      if (data.hasOwnProperty('theme')) {
        obj['theme'] = ApiClient.convertToType(data['theme'], 'String');
      }
      if (data.hasOwnProperty('assignmentsCount')) {
        obj['assignmentsCount'] = ApiClient.convertToType(data['assignmentsCount'], 'Number');
      }
      if (data.hasOwnProperty('studentsGroup')) {
        obj['studentsGroup'] = GroupDetails.constructFromObject(data['studentsGroup']);
      }
      if (data.hasOwnProperty('teachersGroup')) {
        obj['teachersGroup'] = GroupDetails.constructFromObject(data['teachersGroup']);
      }
      if (data.hasOwnProperty('googleClassroom')) {
        obj['googleClassroom'] = ClassDetailsGoogleClassroom.constructFromObject(data['googleClassroom']);
      }
      if (data.hasOwnProperty('googleDrive')) {
        obj['googleDrive'] = ClassDetailsGoogleDrive.constructFromObject(data['googleDrive']);
      }
      if (data.hasOwnProperty('lti')) {
        obj['lti'] = ClassDetailsLti.constructFromObject(data['lti']);
      }
      if (data.hasOwnProperty('canvas')) {
        obj['canvas'] = ClassDetailsCanvas.constructFromObject(data['canvas']);
      }
    }
    return obj;
  }

  /**
   * The unique identifier of the class
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/ClassState} state
   */
  exports.prototype['state'] = undefined;
  /**
   * The name of the class
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The section of the class
   * @member {String} section
   */
  exports.prototype['section'] = undefined;
  /**
   * An optionnal description for this class
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * The unique identifier of the Organization owning this class
   * @member {String} organization
   */
  exports.prototype['organization'] = undefined;
  /**
   * The unique identifier of the User owning this class
   * @member {String} owner
   */
  exports.prototype['owner'] = undefined;
  /**
   * The date when the class was create
   * @member {Date} creationDate
   */
  exports.prototype['creationDate'] = undefined;
  /**
   * [Teachers only] The enrollment code that can be used by the students to join the class 
   * @member {String} enrollmentCode
   */
  exports.prototype['enrollmentCode'] = undefined;
  /**
   * The theme identifier using in Flat User Interface
   * @member {String} theme
   */
  exports.prototype['theme'] = undefined;
  /**
   * The number of assignments created in the class
   * @member {Number} assignmentsCount
   */
  exports.prototype['assignmentsCount'] = undefined;
  /**
   * @member {module:model/GroupDetails} studentsGroup
   */
  exports.prototype['studentsGroup'] = undefined;
  /**
   * @member {module:model/GroupDetails} teachersGroup
   */
  exports.prototype['teachersGroup'] = undefined;
  /**
   * @member {module:model/ClassDetailsGoogleClassroom} googleClassroom
   */
  exports.prototype['googleClassroom'] = undefined;
  /**
   * @member {module:model/ClassDetailsGoogleDrive} googleDrive
   */
  exports.prototype['googleDrive'] = undefined;
  /**
   * @member {module:model/ClassDetailsLti} lti
   */
  exports.prototype['lti'] = undefined;
  /**
   * @member {module:model/ClassDetailsCanvas} canvas
   */
  exports.prototype['canvas'] = undefined;



  return exports;
}));


