/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML or MIDI files * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and interoduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * OpenAPI spec version: 2.6.0
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ScoreCommentContext'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ScoreCommentContext'));
  } else {
    // Browser globals (root is window)
    if (!root.FlatApi) {
      root.FlatApi = {};
    }
    root.FlatApi.ScoreCommentUpdate = factory(root.FlatApi.ApiClient, root.FlatApi.ScoreCommentContext);
  }
}(this, function(ApiClient, ScoreCommentContext) {
  'use strict';




  /**
   * The ScoreCommentUpdate model module.
   * @module model/ScoreCommentUpdate
   * @version 2.6.0
   */

  /**
   * Constructs a new <code>ScoreCommentUpdate</code>.
   * Update of a comment
   * @alias module:model/ScoreCommentUpdate
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>ScoreCommentUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ScoreCommentUpdate} obj Optional instance to populate.
   * @return {module:model/ScoreCommentUpdate} The populated <code>ScoreCommentUpdate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('revision')) {
        obj['revision'] = ApiClient.convertToType(data['revision'], 'String');
      }
      if (data.hasOwnProperty('comment')) {
        obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
      }
      if (data.hasOwnProperty('rawComment')) {
        obj['rawComment'] = ApiClient.convertToType(data['rawComment'], 'String');
      }
      if (data.hasOwnProperty('context')) {
        obj['context'] = ScoreCommentContext.constructFromObject(data['context']);
      }
    }
    return obj;
  }

  /**
   * The unique indentifier of the revision of the score where the comment was added. If this property is unspecified or contains \"last\", the API will automatically take the last revision created. 
   * @member {String} revision
   */
  exports.prototype['revision'] = undefined;
  /**
   * The comment text that can includes mentions using the following format: `@[id:username]`. 
   * @member {String} comment
   */
  exports.prototype['comment'] = undefined;
  /**
   * A raw version of the comment, that can be displayed without the mentions. If you use mentions, this property must be set. 
   * @member {String} rawComment
   */
  exports.prototype['rawComment'] = undefined;
  /**
   * @member {module:model/ScoreCommentContext} context
   */
  exports.prototype['context'] = undefined;



  return exports;
}));


