/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML or MIDI files * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and interoduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * OpenAPI spec version: 2.6.0
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ScoreData', 'model/ScoreDataEncoding', 'model/ScorePrivacy', 'model/ScoreSource'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ScoreData'), require('./ScoreDataEncoding'), require('./ScorePrivacy'), require('./ScoreSource'));
  } else {
    // Browser globals (root is window)
    if (!root.FlatApi) {
      root.FlatApi = {};
    }
    root.FlatApi.ScoreCreation = factory(root.FlatApi.ApiClient, root.FlatApi.ScoreData, root.FlatApi.ScoreDataEncoding, root.FlatApi.ScorePrivacy, root.FlatApi.ScoreSource);
  }
}(this, function(ApiClient, ScoreData, ScoreDataEncoding, ScorePrivacy, ScoreSource) {
  'use strict';




  /**
   * The ScoreCreation model module.
   * @module model/ScoreCreation
   * @version 2.6.0
   */

  /**
   * Constructs a new <code>ScoreCreation</code>.
   * A new created score
   * @alias module:model/ScoreCreation
   * @class
   * @param privacy {module:model/ScorePrivacy} 
   */
  var exports = function(privacy) {
    var _this = this;


    _this['privacy'] = privacy;





  };

  /**
   * Constructs a <code>ScoreCreation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ScoreCreation} obj Optional instance to populate.
   * @return {module:model/ScoreCreation} The populated <code>ScoreCreation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('privacy')) {
        obj['privacy'] = ScorePrivacy.constructFromObject(data['privacy']);
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = ScoreData.constructFromObject(data['data']);
      }
      if (data.hasOwnProperty('dataEncoding')) {
        obj['dataEncoding'] = ScoreDataEncoding.constructFromObject(data['dataEncoding']);
      }
      if (data.hasOwnProperty('source')) {
        obj['source'] = ScoreSource.constructFromObject(data['source']);
      }
      if (data.hasOwnProperty('collection')) {
        obj['collection'] = ApiClient.convertToType(data['collection'], 'String');
      }
      if (data.hasOwnProperty('googleDriveFolder')) {
        obj['googleDriveFolder'] = ApiClient.convertToType(data['googleDriveFolder'], 'String');
      }
    }
    return obj;
  }

  /**
   * The title of the new score. If the title is too long, the API may trim this one.  If this title is not specified, the API will try to (in this order):   - Use the name of the file for files from a specified `source` (e.g. Google Drive)   - Use the title contained in the file (e.g. [`movement-title`](https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-movement-title.htm) or [`credit-words`](https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-credit-words.htm) for [MusicXML](http://www.musicxml.com/) files).   - Set a default title (e.g. \"New Music Score\") 
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {module:model/ScorePrivacy} privacy
   */
  exports.prototype['privacy'] = undefined;
  /**
   * @member {module:model/ScoreData} data
   */
  exports.prototype['data'] = undefined;
  /**
   * @member {module:model/ScoreDataEncoding} dataEncoding
   */
  exports.prototype['dataEncoding'] = undefined;
  /**
   * @member {module:model/ScoreSource} source
   */
  exports.prototype['source'] = undefined;
  /**
   * Unique identifier of a collection where the score will be created. If no collection identifier is provided, the score will be stored in the `root` directory. 
   * @member {String} collection
   */
  exports.prototype['collection'] = undefined;
  /**
   * If the user uses Google Drive and this properties is specified, the file will be created in this directory. The currently user creating the file must be granted to write in this directory. 
   * @member {String} googleDriveFolder
   */
  exports.prototype['googleDriveFolder'] = undefined;



  return exports;
}));


