/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML or MIDI files * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and interoduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * OpenAPI spec version: 2.6.0
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ScoreTrackPoint', 'model/ScoreTrackState'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ScoreTrackPoint'), require('./ScoreTrackState'));
  } else {
    // Browser globals (root is window)
    if (!root.FlatApi) {
      root.FlatApi = {};
    }
    root.FlatApi.ScoreTrackCreation = factory(root.FlatApi.ApiClient, root.FlatApi.ScoreTrackPoint, root.FlatApi.ScoreTrackState);
  }
}(this, function(ApiClient, ScoreTrackPoint, ScoreTrackState) {
  'use strict';




  /**
   * The ScoreTrackCreation model module.
   * @module model/ScoreTrackCreation
   * @version 2.6.0
   */

  /**
   * Constructs a new <code>ScoreTrackCreation</code>.
   * Creation of a new track. This one must contain the URL of the track or the corresponding file 
   * @alias module:model/ScoreTrackCreation
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>ScoreTrackCreation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ScoreTrackCreation} obj Optional instance to populate.
   * @return {module:model/ScoreTrackCreation} The populated <code>ScoreTrackCreation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('default')) {
        obj['default'] = ApiClient.convertToType(data['default'], 'Boolean');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ScoreTrackState.constructFromObject(data['state']);
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('synchronizationPoints')) {
        obj['synchronizationPoints'] = ApiClient.convertToType(data['synchronizationPoints'], [ScoreTrackPoint]);
      }
    }
    return obj;
  }

  /**
   * Title of the track
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * True if the track should be used as default audio source
   * @member {Boolean} default
   */
  exports.prototype['default'] = undefined;
  /**
   * @member {module:model/ScoreTrackState} state
   */
  exports.prototype['state'] = undefined;
  /**
   * The URL of the track
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {Array.<module:model/ScoreTrackPoint>} synchronizationPoints
   */
  exports.prototype['synchronizationPoints'] = undefined;



  return exports;
}));


