/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro (GP3, GP4, GP5, GPX, GP), PowerTab, TuxGuitar and MuseScore files * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and interoduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ScoreTrackPoint from './ScoreTrackPoint';
import ScoreTrackState from './ScoreTrackState';
import ScoreTrackType from './ScoreTrackType';

/**
 * The ScoreTrack model module.
 * @module model/ScoreTrack
 * @version 2.9.0
 */
class ScoreTrack {
    /**
     * Constructs a new <code>ScoreTrack</code>.
     * An audio track for a score
     * @alias module:model/ScoreTrack
     */
    constructor() { 
        
        ScoreTrack.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ScoreTrack</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScoreTrack} obj Optional instance to populate.
     * @return {module:model/ScoreTrack} The populated <code>ScoreTrack</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScoreTrack();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'String');
            }
            if (data.hasOwnProperty('creator')) {
                obj['creator'] = ApiClient.convertToType(data['creator'], 'String');
            }
            if (data.hasOwnProperty('creationDate')) {
                obj['creationDate'] = ApiClient.convertToType(data['creationDate'], 'Date');
            }
            if (data.hasOwnProperty('modificationDate')) {
                obj['modificationDate'] = ApiClient.convertToType(data['modificationDate'], 'Date');
            }
            if (data.hasOwnProperty('default')) {
                obj['default'] = ApiClient.convertToType(data['default'], 'Boolean');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ScoreTrackState.constructFromObject(data['state']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ScoreTrackType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('mediaId')) {
                obj['mediaId'] = ApiClient.convertToType(data['mediaId'], 'String');
            }
            if (data.hasOwnProperty('synchronizationPoints')) {
                obj['synchronizationPoints'] = ApiClient.convertToType(data['synchronizationPoints'], [ScoreTrackPoint]);
            }
        }
        return obj;
    }


}

/**
 * The unique identifier of the score track
 * @member {String} id
 */
ScoreTrack.prototype['id'] = undefined;

/**
 * Title of the track
 * @member {String} title
 */
ScoreTrack.prototype['title'] = undefined;

/**
 * The unique identifier of the score
 * @member {String} score
 */
ScoreTrack.prototype['score'] = undefined;

/**
 * The unique identifier of the track creator
 * @member {String} creator
 */
ScoreTrack.prototype['creator'] = undefined;

/**
 * The creation date of the track
 * @member {Date} creationDate
 */
ScoreTrack.prototype['creationDate'] = undefined;

/**
 * The modification date of the track
 * @member {Date} modificationDate
 */
ScoreTrack.prototype['modificationDate'] = undefined;

/**
 * True if the track should be used as default audio source
 * @member {Boolean} default
 */
ScoreTrack.prototype['default'] = undefined;

/**
 * @member {module:model/ScoreTrackState} state
 */
ScoreTrack.prototype['state'] = undefined;

/**
 * @member {module:model/ScoreTrackType} type
 */
ScoreTrack.prototype['type'] = undefined;

/**
 * The URL of the track
 * @member {String} url
 */
ScoreTrack.prototype['url'] = undefined;

/**
 * The unique identifier of the track when hosted on an external service. For example, if the url is `https://www.youtube.com/watch?v=dQw4w9WgXcQ`, `mediaId` will be `dQw4w9WgXcQ` 
 * @member {String} mediaId
 */
ScoreTrack.prototype['mediaId'] = undefined;

/**
 * @member {Array.<module:model/ScoreTrackPoint>} synchronizationPoints
 */
ScoreTrack.prototype['synchronizationPoints'] = undefined;






export default ScoreTrack;

