/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro (GP3, GP4, GP5, GPX, GP), PowerTab, TuxGuitar and MuseScore files * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and interoduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ClassRoles from './ClassRoles';
import OrganizationRoles from './OrganizationRoles';
import UserDetailsAdminAllOf from './UserDetailsAdminAllOf';
import UserDetailsAdminAllOfLicense from './UserDetailsAdminAllOfLicense';
import UserPublicSummary from './UserPublicSummary';

/**
 * The UserDetailsAdmin model module.
 * @module model/UserDetailsAdmin
 * @version 2.9.0
 */
class UserDetailsAdmin {
    /**
     * Constructs a new <code>UserDetailsAdmin</code>.
     * User details (view for organization teacher / admin)
     * @alias module:model/UserDetailsAdmin
     * @extends module:model/UserPublicSummary
     * @implements module:model/UserPublicSummary
     * @implements module:model/UserDetailsAdminAllOf
     */
    constructor() { 
        UserPublicSummary.initialize(this);UserDetailsAdminAllOf.initialize(this);
        UserDetailsAdmin.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserDetailsAdmin</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserDetailsAdmin} obj Optional instance to populate.
     * @return {module:model/UserDetailsAdmin} The populated <code>UserDetailsAdmin</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserDetailsAdmin();
            UserPublicSummary.constructFromObject(data, obj);
            UserPublicSummary.constructFromObject(data, obj);
            UserDetailsAdminAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('lastActivityDate')) {
                obj['lastActivityDate'] = ApiClient.convertToType(data['lastActivityDate'], 'Date');
            }
            if (data.hasOwnProperty('license')) {
                obj['license'] = UserDetailsAdminAllOfLicense.constructFromObject(data['license']);
            }
        }
        return obj;
    }


}

/**
 * Email of the user
 * @member {String} email
 */
UserDetailsAdmin.prototype['email'] = undefined;

/**
 * Date of the last user activity
 * @member {Date} lastActivityDate
 */
UserDetailsAdmin.prototype['lastActivityDate'] = undefined;

/**
 * @member {module:model/UserDetailsAdminAllOfLicense} license
 */
UserDetailsAdmin.prototype['license'] = undefined;


// Implement UserPublicSummary interface:
/**
 * The user unique identifier
 * @member {String} id
 */
UserPublicSummary.prototype['id'] = undefined;
/**
 * The user name (unique for the organization)
 * @member {String} username
 */
UserPublicSummary.prototype['username'] = undefined;
/**
 * The name that can be directly printed (name, firstname & lastname, or username)
 * @member {String} printableName
 */
UserPublicSummary.prototype['printableName'] = undefined;
/**
 * Firstname of the user (for education users)
 * @member {String} firstname
 */
UserPublicSummary.prototype['firstname'] = undefined;
/**
 * Lastname of the user (for education users)
 * @member {String} lastname
 */
UserPublicSummary.prototype['lastname'] = undefined;
/**
 * A displayable name for the user (for consumer users)
 * @member {String} name
 */
UserPublicSummary.prototype['name'] = undefined;
/**
 * User pictue
 * @member {String} picture
 */
UserPublicSummary.prototype['picture'] = undefined;
/**
 * User license status. 'true' if user is an individual Power user
 * @member {Boolean} isPowerUser
 */
UserPublicSummary.prototype['isPowerUser'] = undefined;
/**
 * Will be 'true' if user is part of the Flat Team
 * @member {Boolean} isFlatTeam
 */
UserPublicSummary.prototype['isFlatTeam'] = undefined;
/**
 * Organization ID (for Edu users only)
 * @member {String} organization
 */
UserPublicSummary.prototype['organization'] = undefined;
/**
 * @member {module:model/OrganizationRoles} organizationRole
 */
UserPublicSummary.prototype['organizationRole'] = undefined;
/**
 * @member {module:model/ClassRoles} classRole
 */
UserPublicSummary.prototype['classRole'] = undefined;
/**
 * Link to user profile (for Indiv. users only)
 * @member {String} htmlUrl
 */
UserPublicSummary.prototype['htmlUrl'] = undefined;
// Implement UserDetailsAdminAllOf interface:
/**
 * Email of the user
 * @member {String} email
 */
UserDetailsAdminAllOf.prototype['email'] = undefined;
/**
 * Date of the last user activity
 * @member {Date} lastActivityDate
 */
UserDetailsAdminAllOf.prototype['lastActivityDate'] = undefined;
/**
 * @member {module:model/UserDetailsAdminAllOfLicense} license
 */
UserDetailsAdminAllOf.prototype['license'] = undefined;




export default UserDetailsAdmin;

