/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro (GP3, GP4, GP5, GPX, GP), PowerTab, TuxGuitar and MuseScore files * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and interoduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ClassRoles from './ClassRoles';
import OrganizationRoles from './OrganizationRoles';
import UserPublicAllOf from './UserPublicAllOf';
import UserPublicSummary from './UserPublicSummary';

/**
 * The UserPublic model module.
 * @module model/UserPublic
 * @version 2.9.0
 */
class UserPublic {
    /**
     * Constructs a new <code>UserPublic</code>.
     * Public User details
     * @alias module:model/UserPublic
     * @extends module:model/UserPublicSummary
     * @implements module:model/UserPublicSummary
     * @implements module:model/UserPublicAllOf
     */
    constructor() { 
        UserPublicSummary.initialize(this);UserPublicAllOf.initialize(this);
        UserPublic.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserPublic</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserPublic} obj Optional instance to populate.
     * @return {module:model/UserPublic} The populated <code>UserPublic</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserPublic();
            UserPublicSummary.constructFromObject(data, obj);
            UserPublicSummary.constructFromObject(data, obj);
            UserPublicAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('bio')) {
                obj['bio'] = ApiClient.convertToType(data['bio'], 'String');
            }
            if (data.hasOwnProperty('registrationDate')) {
                obj['registrationDate'] = ApiClient.convertToType(data['registrationDate'], 'Date');
            }
            if (data.hasOwnProperty('likedScoresCount')) {
                obj['likedScoresCount'] = ApiClient.convertToType(data['likedScoresCount'], 'Number');
            }
            if (data.hasOwnProperty('followersCount')) {
                obj['followersCount'] = ApiClient.convertToType(data['followersCount'], 'Number');
            }
            if (data.hasOwnProperty('followingCount')) {
                obj['followingCount'] = ApiClient.convertToType(data['followingCount'], 'Number');
            }
            if (data.hasOwnProperty('ownedPublicScoresCount')) {
                obj['ownedPublicScoresCount'] = ApiClient.convertToType(data['ownedPublicScoresCount'], 'Number');
            }
            if (data.hasOwnProperty('profileTheme')) {
                obj['profileTheme'] = ApiClient.convertToType(data['profileTheme'], 'String');
            }
            if (data.hasOwnProperty('instruments')) {
                obj['instruments'] = ApiClient.convertToType(data['instruments'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * User's biography
 * @member {String} bio
 */
UserPublic.prototype['bio'] = undefined;

/**
 * Date the user signed up
 * @member {Date} registrationDate
 */
UserPublic.prototype['registrationDate'] = undefined;

/**
 * Number of the scores liked by the user
 * @member {Number} likedScoresCount
 */
UserPublic.prototype['likedScoresCount'] = undefined;

/**
 * Number of followers the user have
 * @member {Number} followersCount
 */
UserPublic.prototype['followersCount'] = undefined;

/**
 * Number of people the user follow
 * @member {Number} followingCount
 */
UserPublic.prototype['followingCount'] = undefined;

/**
 * Number of public scores the user have
 * @member {Number} ownedPublicScoresCount
 */
UserPublic.prototype['ownedPublicScoresCount'] = undefined;

/**
 * Theme (background) for the profile
 * @member {String} profileTheme
 */
UserPublic.prototype['profileTheme'] = undefined;

/**
 * An array of the instrument identifiers that the user plays. This is mainly used to display a list of the instruments in the Flat's UI or instruments icons. The format of the strings is `{instrument-group}.{instrument-id}`. 
 * @member {Array.<String>} instruments
 */
UserPublic.prototype['instruments'] = undefined;


// Implement UserPublicSummary interface:
/**
 * The user unique identifier
 * @member {String} id
 */
UserPublicSummary.prototype['id'] = undefined;
/**
 * The user name (unique for the organization)
 * @member {String} username
 */
UserPublicSummary.prototype['username'] = undefined;
/**
 * The name that can be directly printed (name, firstname & lastname, or username)
 * @member {String} printableName
 */
UserPublicSummary.prototype['printableName'] = undefined;
/**
 * Firstname of the user (for education users)
 * @member {String} firstname
 */
UserPublicSummary.prototype['firstname'] = undefined;
/**
 * Lastname of the user (for education users)
 * @member {String} lastname
 */
UserPublicSummary.prototype['lastname'] = undefined;
/**
 * A displayable name for the user (for consumer users)
 * @member {String} name
 */
UserPublicSummary.prototype['name'] = undefined;
/**
 * User pictue
 * @member {String} picture
 */
UserPublicSummary.prototype['picture'] = undefined;
/**
 * User license status. 'true' if user is an individual Power user
 * @member {Boolean} isPowerUser
 */
UserPublicSummary.prototype['isPowerUser'] = undefined;
/**
 * Will be 'true' if user is part of the Flat Team
 * @member {Boolean} isFlatTeam
 */
UserPublicSummary.prototype['isFlatTeam'] = undefined;
/**
 * Organization ID (for Edu users only)
 * @member {String} organization
 */
UserPublicSummary.prototype['organization'] = undefined;
/**
 * @member {module:model/OrganizationRoles} organizationRole
 */
UserPublicSummary.prototype['organizationRole'] = undefined;
/**
 * @member {module:model/ClassRoles} classRole
 */
UserPublicSummary.prototype['classRole'] = undefined;
/**
 * Link to user profile (for Indiv. users only)
 * @member {String} htmlUrl
 */
UserPublicSummary.prototype['htmlUrl'] = undefined;
// Implement UserPublicAllOf interface:
/**
 * User's biography
 * @member {String} bio
 */
UserPublicAllOf.prototype['bio'] = undefined;
/**
 * Date the user signed up
 * @member {Date} registrationDate
 */
UserPublicAllOf.prototype['registrationDate'] = undefined;
/**
 * Number of the scores liked by the user
 * @member {Number} likedScoresCount
 */
UserPublicAllOf.prototype['likedScoresCount'] = undefined;
/**
 * Number of followers the user have
 * @member {Number} followersCount
 */
UserPublicAllOf.prototype['followersCount'] = undefined;
/**
 * Number of people the user follow
 * @member {Number} followingCount
 */
UserPublicAllOf.prototype['followingCount'] = undefined;
/**
 * Number of public scores the user have
 * @member {Number} ownedPublicScoresCount
 */
UserPublicAllOf.prototype['ownedPublicScoresCount'] = undefined;
/**
 * Theme (background) for the profile
 * @member {String} profileTheme
 */
UserPublicAllOf.prototype['profileTheme'] = undefined;
/**
 * An array of the instrument identifiers that the user plays. This is mainly used to display a list of the instruments in the Flat's UI or instruments icons. The format of the strings is `{instrument-group}.{instrument-id}`. 
 * @member {Array.<String>} instruments
 */
UserPublicAllOf.prototype['instruments'] = undefined;




export default UserPublic;

