/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.1
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type Assignment,
    AssignmentFromJSON,
    AssignmentToJSON,
} from '../models/Assignment.js';
import {
    type AssignmentType,
    AssignmentTypeFromJSON,
    AssignmentTypeToJSON,
} from '../models/AssignmentType.js';
import {
    type AssignmentUpdate,
    AssignmentUpdateFromJSON,
    AssignmentUpdateToJSON,
} from '../models/AssignmentUpdate.js';
import {
    type ClassAssignment,
    ClassAssignmentFromJSON,
    ClassAssignmentToJSON,
} from '../models/ClassAssignment.js';
import {
    type EduLibrary,
    EduLibraryFromJSON,
    EduLibraryToJSON,
} from '../models/EduLibrary.js';
import {
    type EduResource,
    EduResourceFromJSON,
    EduResourceToJSON,
} from '../models/EduResource.js';
import {
    type EduResourceCopy,
    EduResourceCopyFromJSON,
    EduResourceCopyToJSON,
} from '../models/EduResourceCopy.js';
import {
    type EduResourceCreation,
    EduResourceCreationFromJSON,
    EduResourceCreationToJSON,
} from '../models/EduResourceCreation.js';
import {
    type EduResourceLtiLink,
    EduResourceLtiLinkFromJSON,
    EduResourceLtiLinkToJSON,
} from '../models/EduResourceLtiLink.js';
import {
    type EduResourceMove,
    EduResourceMoveFromJSON,
    EduResourceMoveToJSON,
} from '../models/EduResourceMove.js';
import {
    type EduResourceUpdate,
    EduResourceUpdateFromJSON,
    EduResourceUpdateToJSON,
} from '../models/EduResourceUpdate.js';
import {
    type EduResourceUseInClass,
    EduResourceUseInClassFromJSON,
    EduResourceUseInClassToJSON,
} from '../models/EduResourceUseInClass.js';
import {
    type FlatErrorResponse,
    FlatErrorResponseFromJSON,
    FlatErrorResponseToJSON,
} from '../models/FlatErrorResponse.js';
import {
    type Grade,
    GradeFromJSON,
    GradeToJSON,
} from '../models/Grade.js';
import {
    type TeachingTheme,
    TeachingThemeFromJSON,
    TeachingThemeToJSON,
} from '../models/TeachingTheme.js';

export interface CopyEduResourceRequest {
    resource: string;
    eduResourceCopy: EduResourceCopy;
}

export interface CopyEduResourceToDemoClassRequest {
    resource: string;
}

export interface CreateEduResourceRequest {
    eduResourceCreation: EduResourceCreation;
}

export interface CreateEduResourceLtiLinkRequest {
    resource: string;
}

export interface DeleteEduResourceRequest {
    resource: string;
}

export interface GetEduResourceRequest {
    resource: string;
}

export interface ListEduResourcesRequest {
    parent?: string;
    withoutSubfoldersResources?: boolean;
    type?: ListEduResourcesTypeEnum;
    subjects?: Array<TeachingTheme>;
    assignmentTypes?: Array<AssignmentType>;
    grades?: Array<Grade>;
    sort?: ListEduResourcesSortEnum;
    direction?: ListEduResourcesDirectionEnum;
    limit?: number;
    next?: string;
    previous?: string;
}

export interface MoveEduResourceRequest {
    resource: string;
    eduResourceMove: EduResourceMove;
}

export interface UpdateEduResourceRequest {
    resource: string;
    eduResourceUpdate: EduResourceUpdate;
}

export interface UpdateEduResourceAssignmentRequest {
    resource: string;
    assignmentUpdate: AssignmentUpdate;
}

export interface UseEduResourceInClassRequest {
    resource: string;
    eduResourceUseInClass: EduResourceUseInClass;
}

/**
 * 
 */
export class EduResourcesApi extends runtime.BaseAPI {

    /**
     * Creates request options for copyEduResource without sending the request
     */
    async copyEduResourceRequestOpts(requestParameters: CopyEduResourceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resource'] == null) {
            throw new runtime.RequiredError(
                'resource',
                'Required parameter "resource" was null or undefined when calling copyEduResource().'
            );
        }

        if (requestParameters['eduResourceCopy'] == null) {
            throw new runtime.RequiredError(
                'eduResourceCopy',
                'Required parameter "eduResourceCopy" was null or undefined when calling copyEduResource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["edu.resources", "edu.assignments"]);
        }


        let urlPath = `/eduResources/{resource}/copy`;
        urlPath = urlPath.replace('{resource}', encodeURIComponent(String(requestParameters['resource'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EduResourceCopyToJSON(requestParameters['eduResourceCopy']),
        };
    }

    /**
     * Copy an education resource to a Resource Library
     */
    async copyEduResourceRaw(requestParameters: CopyEduResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EduResource>> {
        const requestOptions = await this.copyEduResourceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EduResourceFromJSON(jsonValue));
    }

    /**
     * Copy an education resource to a Resource Library
     */
    async copyEduResource(requestParameters: CopyEduResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EduResource> {
        const response = await this.copyEduResourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for copyEduResourceToDemoClass without sending the request
     */
    async copyEduResourceToDemoClassRequestOpts(requestParameters: CopyEduResourceToDemoClassRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resource'] == null) {
            throw new runtime.RequiredError(
                'resource',
                'Required parameter "resource" was null or undefined when calling copyEduResourceToDemoClass().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["edu.resources", "edu.assignments"]);
        }


        let urlPath = `/eduResources/{resource}/copyToDemoClass`;
        urlPath = urlPath.replace('{resource}', encodeURIComponent(String(requestParameters['resource'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Once a resource library can be published to a class (`Assignment.capabilities.canPublishInClass = true`), this endpoint can be used for the feature \"View as student\".  It will ensure the teacher has a demo class, then copy the assignment to the demo class. You can then use `POST /classes/{class}/testStudent` to create a testing student account in the demo class. 
     * Copy an education assignment to a teacher demo class
     */
    async copyEduResourceToDemoClassRaw(requestParameters: CopyEduResourceToDemoClassRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClassAssignment>> {
        const requestOptions = await this.copyEduResourceToDemoClassRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClassAssignmentFromJSON(jsonValue));
    }

    /**
     * Once a resource library can be published to a class (`Assignment.capabilities.canPublishInClass = true`), this endpoint can be used for the feature \"View as student\".  It will ensure the teacher has a demo class, then copy the assignment to the demo class. You can then use `POST /classes/{class}/testStudent` to create a testing student account in the demo class. 
     * Copy an education assignment to a teacher demo class
     */
    async copyEduResourceToDemoClass(requestParameters: CopyEduResourceToDemoClassRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClassAssignment> {
        const response = await this.copyEduResourceToDemoClassRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createEduResource without sending the request
     */
    async createEduResourceRequestOpts(requestParameters: CreateEduResourceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eduResourceCreation'] == null) {
            throw new runtime.RequiredError(
                'eduResourceCreation',
                'Required parameter "eduResourceCreation" was null or undefined when calling createEduResource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["edu.resources", "edu.assignments"]);
        }


        let urlPath = `/eduResources`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EduResourceCreationToJSON(requestParameters['eduResourceCreation']),
        };
    }

    /**
     * Create a new education resource
     */
    async createEduResourceRaw(requestParameters: CreateEduResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EduResource>> {
        const requestOptions = await this.createEduResourceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EduResourceFromJSON(jsonValue));
    }

    /**
     * Create a new education resource
     */
    async createEduResource(requestParameters: CreateEduResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EduResource> {
        const response = await this.createEduResourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createEduResourceLtiLink without sending the request
     */
    async createEduResourceLtiLinkRequestOpts(requestParameters: CreateEduResourceLtiLinkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resource'] == null) {
            throw new runtime.RequiredError(
                'resource',
                'Required parameter "resource" was null or undefined when calling createEduResourceLtiLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["edu.resources", "edu.assignments"]);
        }


        let urlPath = `/eduResources/{resource}/createLtiLink`;
        urlPath = urlPath.replace('{resource}', encodeURIComponent(String(requestParameters['resource'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This endpoint will return an LTI link that can be used to launch Flat for Education. The link, in a context from a class, will ensure the assignment has been copied in the class. 
     * Create an LTI link for an education resource
     */
    async createEduResourceLtiLinkRaw(requestParameters: CreateEduResourceLtiLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EduResourceLtiLink>> {
        const requestOptions = await this.createEduResourceLtiLinkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EduResourceLtiLinkFromJSON(jsonValue));
    }

    /**
     * This endpoint will return an LTI link that can be used to launch Flat for Education. The link, in a context from a class, will ensure the assignment has been copied in the class. 
     * Create an LTI link for an education resource
     */
    async createEduResourceLtiLink(requestParameters: CreateEduResourceLtiLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EduResourceLtiLink> {
        const response = await this.createEduResourceLtiLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteEduResource without sending the request
     */
    async deleteEduResourceRequestOpts(requestParameters: DeleteEduResourceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resource'] == null) {
            throw new runtime.RequiredError(
                'resource',
                'Required parameter "resource" was null or undefined when calling deleteEduResource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["edu.resources", "edu.assignments"]);
        }


        let urlPath = `/eduResources/{resource}`;
        urlPath = urlPath.replace('{resource}', encodeURIComponent(String(requestParameters['resource'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete an education resource
     */
    async deleteEduResourceRaw(requestParameters: DeleteEduResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteEduResourceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an education resource
     */
    async deleteEduResource(requestParameters: DeleteEduResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteEduResourceRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getEduResource without sending the request
     */
    async getEduResourceRequestOpts(requestParameters: GetEduResourceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resource'] == null) {
            throw new runtime.RequiredError(
                'resource',
                'Required parameter "resource" was null or undefined when calling getEduResource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["edu.resources", "edu.resources.readonly", "edu.assignments", "edu.assignments.readonly"]);
        }


        let urlPath = `/eduResources/{resource}`;
        urlPath = urlPath.replace('{resource}', encodeURIComponent(String(requestParameters['resource'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get an education resource
     */
    async getEduResourceRaw(requestParameters: GetEduResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EduResource>> {
        const requestOptions = await this.getEduResourceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EduResourceFromJSON(jsonValue));
    }

    /**
     * Get an education resource
     */
    async getEduResource(requestParameters: GetEduResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EduResource> {
        const response = await this.getEduResourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listEduLibraries without sending the request
     */
    async listEduLibrariesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["edu.resources", "edu.resources.readonly", "edu.assignments", "edu.assignments.readonly"]);
        }


        let urlPath = `/eduResources/libraries`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the education libraries
     */
    async listEduLibrariesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EduLibrary>>> {
        const requestOptions = await this.listEduLibrariesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EduLibraryFromJSON));
    }

    /**
     * List the education libraries
     */
    async listEduLibraries(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EduLibrary>> {
        const response = await this.listEduLibrariesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listEduResources without sending the request
     */
    async listEduResourcesRequestOpts(requestParameters: ListEduResourcesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['parent'] != null) {
            queryParameters['parent'] = requestParameters['parent'];
        }

        if (requestParameters['withoutSubfoldersResources'] != null) {
            queryParameters['withoutSubfoldersResources'] = requestParameters['withoutSubfoldersResources'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['subjects'] != null) {
            queryParameters['subjects'] = requestParameters['subjects'];
        }

        if (requestParameters['assignmentTypes'] != null) {
            queryParameters['assignmentTypes'] = requestParameters['assignmentTypes'];
        }

        if (requestParameters['grades'] != null) {
            queryParameters['grades'] = requestParameters['grades'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['next'] != null) {
            queryParameters['next'] = requestParameters['next'];
        }

        if (requestParameters['previous'] != null) {
            queryParameters['previous'] = requestParameters['previous'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["edu.resources", "edu.resources.readonly", "edu.assignments", "edu.assignments.readonly"]);
        }


        let urlPath = `/eduResources`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List education resources in a library or folder
     */
    async listEduResourcesRaw(requestParameters: ListEduResourcesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EduResource>>> {
        const requestOptions = await this.listEduResourcesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EduResourceFromJSON));
    }

    /**
     * List education resources in a library or folder
     */
    async listEduResources(requestParameters: ListEduResourcesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EduResource>> {
        const response = await this.listEduResourcesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for moveEduResource without sending the request
     */
    async moveEduResourceRequestOpts(requestParameters: MoveEduResourceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resource'] == null) {
            throw new runtime.RequiredError(
                'resource',
                'Required parameter "resource" was null or undefined when calling moveEduResource().'
            );
        }

        if (requestParameters['eduResourceMove'] == null) {
            throw new runtime.RequiredError(
                'eduResourceMove',
                'Required parameter "eduResourceMove" was null or undefined when calling moveEduResource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["edu.resources", "edu.assignments"]);
        }


        let urlPath = `/eduResources/{resource}/move`;
        urlPath = urlPath.replace('{resource}', encodeURIComponent(String(requestParameters['resource'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EduResourceMoveToJSON(requestParameters['eduResourceMove']),
        };
    }

    /**
     * Move an education resource
     */
    async moveEduResourceRaw(requestParameters: MoveEduResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EduResource>> {
        const requestOptions = await this.moveEduResourceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EduResourceFromJSON(jsonValue));
    }

    /**
     * Move an education resource
     */
    async moveEduResource(requestParameters: MoveEduResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EduResource> {
        const response = await this.moveEduResourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateEduResource without sending the request
     */
    async updateEduResourceRequestOpts(requestParameters: UpdateEduResourceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resource'] == null) {
            throw new runtime.RequiredError(
                'resource',
                'Required parameter "resource" was null or undefined when calling updateEduResource().'
            );
        }

        if (requestParameters['eduResourceUpdate'] == null) {
            throw new runtime.RequiredError(
                'eduResourceUpdate',
                'Required parameter "eduResourceUpdate" was null or undefined when calling updateEduResource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["edu.resources", "edu.assignments"]);
        }


        let urlPath = `/eduResources/{resource}`;
        urlPath = urlPath.replace('{resource}', encodeURIComponent(String(requestParameters['resource'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EduResourceUpdateToJSON(requestParameters['eduResourceUpdate']),
        };
    }

    /**
     * Update any resources metadata (e.g. title).  Use this method to rename education resources folders or assignments. 
     * Update an education resource metadata
     */
    async updateEduResourceRaw(requestParameters: UpdateEduResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EduResource>> {
        const requestOptions = await this.updateEduResourceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EduResourceFromJSON(jsonValue));
    }

    /**
     * Update any resources metadata (e.g. title).  Use this method to rename education resources folders or assignments. 
     * Update an education resource metadata
     */
    async updateEduResource(requestParameters: UpdateEduResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EduResource> {
        const response = await this.updateEduResourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateEduResourceAssignment without sending the request
     */
    async updateEduResourceAssignmentRequestOpts(requestParameters: UpdateEduResourceAssignmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resource'] == null) {
            throw new runtime.RequiredError(
                'resource',
                'Required parameter "resource" was null or undefined when calling updateEduResourceAssignment().'
            );
        }

        if (requestParameters['assignmentUpdate'] == null) {
            throw new runtime.RequiredError(
                'assignmentUpdate',
                'Required parameter "assignmentUpdate" was null or undefined when calling updateEduResourceAssignment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["edu.resources", "edu.assignments"]);
        }


        let urlPath = `/eduResources/{resource}/assignment`;
        urlPath = urlPath.replace('{resource}', encodeURIComponent(String(requestParameters['resource'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AssignmentUpdateToJSON(requestParameters['assignmentUpdate']),
        };
    }

    /**
     * Update an education resource assignment
     */
    async updateEduResourceAssignmentRaw(requestParameters: UpdateEduResourceAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assignment>> {
        const requestOptions = await this.updateEduResourceAssignmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssignmentFromJSON(jsonValue));
    }

    /**
     * Update an education resource assignment
     */
    async updateEduResourceAssignment(requestParameters: UpdateEduResourceAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assignment> {
        const response = await this.updateEduResourceAssignmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for useEduResourceInClass without sending the request
     */
    async useEduResourceInClassRequestOpts(requestParameters: UseEduResourceInClassRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resource'] == null) {
            throw new runtime.RequiredError(
                'resource',
                'Required parameter "resource" was null or undefined when calling useEduResourceInClass().'
            );
        }

        if (requestParameters['eduResourceUseInClass'] == null) {
            throw new runtime.RequiredError(
                'eduResourceUseInClass',
                'Required parameter "eduResourceUseInClass" was null or undefined when calling useEduResourceInClass().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["edu.resources", "edu.assignments"]);
        }


        let urlPath = `/eduResources/{resource}/useInClass`;
        urlPath = urlPath.replace('{resource}', encodeURIComponent(String(requestParameters['resource'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EduResourceUseInClassToJSON(requestParameters['eduResourceUseInClass']),
        };
    }

    /**
     * This endpoint will copy a resource and the underlying resources. The assignment will be created as a draft that can be completed with other options before publishing (e.g. due date, publication date for scheduling, etc.). 
     * Use an education resource in a class
     */
    async useEduResourceInClassRaw(requestParameters: UseEduResourceInClassRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClassAssignment>> {
        const requestOptions = await this.useEduResourceInClassRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClassAssignmentFromJSON(jsonValue));
    }

    /**
     * This endpoint will copy a resource and the underlying resources. The assignment will be created as a draft that can be completed with other options before publishing (e.g. due date, publication date for scheduling, etc.). 
     * Use an education resource in a class
     */
    async useEduResourceInClass(requestParameters: UseEduResourceInClassRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClassAssignment> {
        const response = await this.useEduResourceInClassRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListEduResourcesTypeEnum = {
    Assignment: 'assignment',
    Folder: 'folder'
} as const;
export type ListEduResourcesTypeEnum = typeof ListEduResourcesTypeEnum[keyof typeof ListEduResourcesTypeEnum];
/**
 * @export
 */
export const ListEduResourcesSortEnum = {
    CreationDate: 'creationDate',
    UpdateDate: 'updateDate',
    Title: 'title'
} as const;
export type ListEduResourcesSortEnum = typeof ListEduResourcesSortEnum[keyof typeof ListEduResourcesSortEnum];
/**
 * @export
 */
export const ListEduResourcesDirectionEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListEduResourcesDirectionEnum = typeof ListEduResourcesDirectionEnum[keyof typeof ListEduResourcesDirectionEnum];
