/* tslint:disable */
/* eslint-disable */
export * from './AccountApi.js';
export * from './ClassApi.js';
export * from './CollectionApi.js';
export * from './EduResourcesApi.js';
export * from './GroupApi.js';
export * from './OMRApi.js';
export * from './OrganizationApi.js';
export * from './ScoreApi.js';
export * from './TaskApi.js';
export * from './UserApi.js';

// BEGIN generated by tools/patches/85_barrel_dedup.py
// Operations carrying two tags are emitted into both tag modules. These names are
// identical in each, so one explicit re-export resolves the TS2308 ambiguity.
export { GetGroupScoresRequest } from './GroupApi.js';
export { GetScoreSubmissionsRequest } from './ClassApi.js';
export { GetUserLikesRequest } from './ScoreApi.js';
export { GetUserScoresDirectionEnum } from './ScoreApi.js';
export { GetUserScoresRequest } from './ScoreApi.js';
export { GetUserScoresSortEnum } from './ScoreApi.js';
// END generated by tools/patches/85_barrel_dedup.py
