/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.1
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type FlatErrorResponse,
    FlatErrorResponseFromJSON,
    FlatErrorResponseToJSON,
} from '../models/FlatErrorResponse.js';
import {
    type ScoreDetails,
    ScoreDetailsFromJSON,
    ScoreDetailsToJSON,
} from '../models/ScoreDetails.js';
import {
    type UserPublic,
    UserPublicFromJSON,
    UserPublicToJSON,
} from '../models/UserPublic.js';

export interface GetUserRequest {
    user: string;
}

export interface GetUserLikesRequest {
    user: string;
    next?: string;
    previous?: string;
    limit?: number;
    ids?: boolean;
}

export interface GetUserScoresRequest {
    user: string;
    paginate?: boolean;
    sort?: GetUserScoresSortEnum;
    direction?: GetUserScoresDirectionEnum;
    limit?: number;
    next?: string;
    previous?: string;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * Creates request options for getUser without sending the request
     */
    async getUserRequestOpts(requestParameters: GetUserRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling getUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["account.public_profile", "account.education_profile"]);
        }


        let urlPath = `/users/{user}`;
        urlPath = urlPath.replace('{user}', encodeURIComponent(String(requestParameters['user'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a profile of a Flat or Flat for Education User. 
     * Get a public user profile
     */
    async getUserRaw(requestParameters: GetUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPublic>> {
        const requestOptions = await this.getUserRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserPublicFromJSON(jsonValue));
    }

    /**
     * Get a profile of a Flat or Flat for Education User. 
     * Get a public user profile
     */
    async getUser(requestParameters: GetUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPublic> {
        const response = await this.getUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUserLikes without sending the request
     */
    async getUserLikesRequestOpts(requestParameters: GetUserLikesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling getUserLikes().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['next'] != null) {
            queryParameters['next'] = requestParameters['next'];
        }

        if (requestParameters['previous'] != null) {
            queryParameters['previous'] = requestParameters['previous'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["account.public_profile"]);
        }


        let urlPath = `/users/{user}/likes`;
        urlPath = urlPath.replace('{user}', encodeURIComponent(String(requestParameters['user'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List liked scores
     */
    async getUserLikesRaw(requestParameters: GetUserLikesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ScoreDetails>>> {
        const requestOptions = await this.getUserLikesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ScoreDetailsFromJSON));
    }

    /**
     * List liked scores
     */
    async getUserLikes(requestParameters: GetUserLikesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ScoreDetails>> {
        const response = await this.getUserLikesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUserScores without sending the request
     */
    async getUserScoresRequestOpts(requestParameters: GetUserScoresRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling getUserScores().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['paginate'] != null) {
            queryParameters['paginate'] = requestParameters['paginate'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['next'] != null) {
            queryParameters['next'] = requestParameters['next'];
        }

        if (requestParameters['previous'] != null) {
            queryParameters['previous'] = requestParameters['previous'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["scores", "scores.readonly"]);
        }


        let urlPath = `/users/{user}/scores`;
        urlPath = urlPath.replace('{user}', encodeURIComponent(String(requestParameters['user'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the list of public scores owned by a User. If you want to access to private scores, please use the [Collections API](#tag/Collection). For example `GET /v2/collections/allScores/scores` to list all recently updated scores. 
     * List user\'s scores
     */
    async getUserScoresRaw(requestParameters: GetUserScoresRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ScoreDetails>>> {
        const requestOptions = await this.getUserScoresRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ScoreDetailsFromJSON));
    }

    /**
     * Get the list of public scores owned by a User. If you want to access to private scores, please use the [Collections API](#tag/Collection). For example `GET /v2/collections/allScores/scores` to list all recently updated scores. 
     * List user\'s scores
     */
    async getUserScores(requestParameters: GetUserScoresRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ScoreDetails>> {
        const response = await this.getUserScoresRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetUserScoresSortEnum = {
    CreationDate: 'creationDate',
    ModificationDate: 'modificationDate',
    Title: 'title'
} as const;
export type GetUserScoresSortEnum = typeof GetUserScoresSortEnum[keyof typeof GetUserScoresSortEnum];
/**
 * @export
 */
export const GetUserScoresDirectionEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type GetUserScoresDirectionEnum = typeof GetUserScoresDirectionEnum[keyof typeof GetUserScoresDirectionEnum];
