/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful: it has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference are [available on GitHub](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.2
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Available scopes
 * @export
 */
export const AppScopes = {
    AccountPublicProfile: 'account.public_profile',
    AccountEmail: 'account.email',
    AccountEducationProfile: 'account.education_profile',
    ScoresReadonly: 'scores.readonly',
    ScoresSocial: 'scores.social',
    Scores: 'scores',
    CollectionsReadonly: 'collections.readonly',
    CollectionsAddScores: 'collections.add_scores',
    Collections: 'collections',
    NotificationsReadonly: 'notifications.readonly',
    EduResources: 'edu.resources',
    EduResourcesReadonly: 'edu.resources.readonly',
    EduClasses: 'edu.classes',
    EduClassesReadonly: 'edu.classes.readonly',
    EduAssignments: 'edu.assignments',
    EduAssignmentsReadonly: 'edu.assignments.readonly',
    EduAdmin: 'edu.admin',
    EduAdminLti: 'edu.admin.lti',
    EduAdminLtiReadonly: 'edu.admin.lti.readonly',
    EduAdminUsers: 'edu.admin.users',
    EduAdminUsersReadonly: 'edu.admin.users.readonly',
    TasksReadonly: 'tasks.readonly',
    Omr: 'omr'
} as const;
export type AppScopes = typeof AppScopes[keyof typeof AppScopes];


export function instanceOfAppScopes(value: any): boolean {
    for (const key in AppScopes) {
        if (Object.prototype.hasOwnProperty.call(AppScopes, key)) {
            if (AppScopes[key as keyof typeof AppScopes] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppScopesFromJSON(json: any): AppScopes {
    return AppScopesFromJSONTyped(json, false);
}

export function AppScopesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppScopes {
    return json as AppScopes;
}

export function AppScopesToJSON(value?: AppScopes | null): any {
    return value as any;
}

export function AppScopesToJSONTyped(value: any, ignoreDiscriminator: boolean): AppScopes {
    return value as AppScopes;
}

