/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful: it has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference are [available on GitHub](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.2
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AssignmentType } from './AssignmentType.js';
import {
    AssignmentTypeFromJSON,
    AssignmentTypeFromJSONTyped,
    AssignmentTypeToJSON,
    AssignmentTypeToJSONTyped,
} from './AssignmentType.js';
import type { AssignmentSubmissionStudentsMode } from './AssignmentSubmissionStudentsMode.js';
import {
    AssignmentSubmissionStudentsModeFromJSON,
    AssignmentSubmissionStudentsModeFromJSONTyped,
    AssignmentSubmissionStudentsModeToJSON,
    AssignmentSubmissionStudentsModeToJSONTyped,
} from './AssignmentSubmissionStudentsMode.js';
import type { ClassAttachmentCreation } from './ClassAttachmentCreation.js';
import {
    ClassAttachmentCreationFromJSON,
    ClassAttachmentCreationFromJSONTyped,
    ClassAttachmentCreationToJSON,
    ClassAttachmentCreationToJSONTyped,
} from './ClassAttachmentCreation.js';

/**
 * Assignment Resource Editing
 * @export
 * @interface AssignmentUpdate
 */
export interface AssignmentUpdate {
    /**
     * 
     * @type {AssignmentType}
     * @memberof AssignmentUpdate
     */
    type?: AssignmentType;
    /**
     * Title of the assignment
     * @type {string}
     * @memberof AssignmentUpdate
     */
    title?: string;
    /**
     * Student instructions and content of the assignment (plain text)
     * @type {string}
     * @memberof AssignmentUpdate
     */
    description?: string;
    /**
     * HTML version of student instructions.
     * Pasted images may be sent as inline base64 `data:` URIs; they are uploaded to storage
     * and rewritten to hosted URLs on save. The final HTML is limited to 100000 characters.
     * When provided, the plain text version will be automatically extracted for compatibility.
     * 
     * @type {string}
     * @memberof AssignmentUpdate
     */
    descriptionHtml?: string;
    /**
     * Teacher-only instructions (plain text)
     * @type {string}
     * @memberof AssignmentUpdate
     */
    teacherInstructions?: string;
    /**
     * HTML version of teacher-only instructions.
     * Pasted images may be sent as inline base64 `data:` URIs; they are uploaded to storage
     * and rewritten to hosted URLs on save. The final HTML is limited to 100000 characters.
     * When provided, the plain text version will be automatically extracted for compatibility.
     * 
     * @type {string}
     * @memberof AssignmentUpdate
     */
    teacherInstructionsHtml?: string;
    /**
     * The complete attachment list. Omitting this property on an update leaves the existing
     * attachments alone; sending it replaces them.
     * 
     * Dropping a dedicated score from the list deletes the students' copies of it, so send the
     * full set you want to keep rather than only the additions. Duplicates, judged by `url`,
     * `score`, `worksheet` or `googleDriveFileId`, are discarded silently, and exceeding the
     * per-assignment limit fails with `ASSIGNMENT_ATTACHMENTS_LIMIT`.
     * 
     * @type {Array<ClassAttachmentCreation>}
     * @memberof AssignmentUpdate
     */
    attachments?: Array<ClassAttachmentCreation>;
    /**
     * The number of playbacks authorized on the scores of the assignment.
     * @type {number}
     * @memberof AssignmentUpdate
     */
    nbPlaybackAuthorized?: number | null;
    /**
     * Restrict the ability to get an audio feedback every time a student adds or selects a note.
     * @type {boolean}
     * @memberof AssignmentUpdate
     */
    restrictPlayNote?: boolean;
    /**
     * Restrict the audio source to provided audio tracks on a score. Students won't be able to use the editor playback.
     * @type {boolean}
     * @memberof AssignmentUpdate
     */
    restrictToAudioTracks?: boolean;
    /**
     * The id of the toolset to apply to this assignment.
     * The toolset will be copied to the assignment as a dedicated object to prevent unexpected changes when making modifications to the template toolset.
     * This property can be set to null to delete the linked toolset and switch back to all the tools available for this assignment.
     * 
     * @type {string}
     * @memberof AssignmentUpdate
     */
    toolset?: string | null;
    /**
     * The id of the cover to display
     * @type {string}
     * @memberof AssignmentUpdate
     */
    coverFile?: string | null;
    /**
     * The URL of the cover to display
     * @type {string}
     * @memberof AssignmentUpdate
     */
    cover?: string | null;
    /**
     * If set, the grading will be enabled for the assignment with this value as the maximum of points
     * 
     * @type {number}
     * @memberof AssignmentUpdate
     */
    maxPoints?: number | null;
    /**
     * For worksheets, how grading will work for the assignment:
     * - If set to `auto`, the grades will be automatically released when the student submits the submissions
     * - If set to `manual`, the grades will only be set as `draftGrade` and will be released when the teacher returns the submissions
     * 
     * @type {AssignmentUpdateReleaseGradesEnum}
     * @memberof AssignmentUpdate
     */
    releaseGrades?: AssignmentUpdateReleaseGradesEnum;
    /**
     * Shuffle the worksheet exercises for each student
     * @type {boolean}
     * @memberof AssignmentUpdate
     */
    shuffleExercises?: boolean;
    /**
     * 
     * @type {AssignmentSubmissionStudentsMode}
     * @memberof AssignmentUpdate
     */
    submissionStudentsMode?: AssignmentSubmissionStudentsMode;
    /**
     * For performance assignments: recording type that will be either 'audio' or 'video'.
     * 
     * * `audio`: Only audio will be required during the recording.
     * * `video`: Camera will be required during the recording.
     * 
     * Only set when type is 'performance'.
     * 
     * @type {AssignmentUpdateRecordingTypeEnum}
     * @memberof AssignmentUpdate
     */
    recordingType?: AssignmentUpdateRecordingTypeEnum;
    /**
     * For performance assignments: Enable students to use the metronome while they are recording,
     * helping them stay in time.
     * Only set when type is 'performance'.
     * 
     * @type {boolean}
     * @memberof AssignmentUpdate
     */
    allowMetronome?: boolean;
    /**
     * For performance assignments: Enable students to listen to the accompaniment without their
     * instrument part while they are playing.
     * Only set when type is 'performance'.
     * 
     * @type {boolean}
     * @memberof AssignmentUpdate
     */
    allowBackingTrack?: boolean;
    /**
     * For performance assignments: whether students can adjust the playback speed of the score during recording.
     * 
     * * `true`: Students can change the tempo/speed during practice and recording
     * * `false`: Tempo is fixed to the original score tempo
     * 
     * Only set when type is 'performance'.
     * 
     * @type {boolean}
     * @memberof AssignmentUpdate
     */
    allowSpeedChange?: boolean;
    /**
     * For performance assignments: "Free Record" mode.
     * 
     * When `true`, no score is attached to the assignment. Students freely record a varied
     * repertoire or an ensemble performance without being constrained by a single score's
     * structure or duration, and all score-dependent options (playback, metronome, backtracking,
     * speed control) are hidden.
     * 
     * Only set when type is 'performance'.
     * 
     * @type {boolean}
     * @memberof AssignmentUpdate
     */
    freeRecord?: boolean;
}


/**
 * @export
 */
export const AssignmentUpdateReleaseGradesEnum = {
    Auto: 'auto',
    Manual: 'manual'
} as const;
export type AssignmentUpdateReleaseGradesEnum = typeof AssignmentUpdateReleaseGradesEnum[keyof typeof AssignmentUpdateReleaseGradesEnum];

/**
 * @export
 */
export const AssignmentUpdateRecordingTypeEnum = {
    Audio: 'audio',
    Video: 'video'
} as const;
export type AssignmentUpdateRecordingTypeEnum = typeof AssignmentUpdateRecordingTypeEnum[keyof typeof AssignmentUpdateRecordingTypeEnum];


/**
 * Check if a given object implements the AssignmentUpdate interface.
 */
export function instanceOfAssignmentUpdate(value: object): value is AssignmentUpdate {
    return true;
}

export function AssignmentUpdateFromJSON(json: any): AssignmentUpdate {
    return AssignmentUpdateFromJSONTyped(json, false);
}

export function AssignmentUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignmentUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : AssignmentTypeFromJSON(json['type']),
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'descriptionHtml': json['descriptionHtml'] == null ? undefined : json['descriptionHtml'],
        'teacherInstructions': json['teacherInstructions'] == null ? undefined : json['teacherInstructions'],
        'teacherInstructionsHtml': json['teacherInstructionsHtml'] == null ? undefined : json['teacherInstructionsHtml'],
        'attachments': json['attachments'] == null ? undefined : ((json['attachments'] as Array<any>).map(ClassAttachmentCreationFromJSON)),
        'nbPlaybackAuthorized': json['nbPlaybackAuthorized'] === undefined ? undefined : json['nbPlaybackAuthorized'] === null ? null : json['nbPlaybackAuthorized'],
        'restrictPlayNote': json['restrictPlayNote'] == null ? undefined : json['restrictPlayNote'],
        'restrictToAudioTracks': json['restrictToAudioTracks'] == null ? undefined : json['restrictToAudioTracks'],
        'toolset': json['toolset'] === undefined ? undefined : json['toolset'] === null ? null : json['toolset'],
        'coverFile': json['coverFile'] === undefined ? undefined : json['coverFile'] === null ? null : json['coverFile'],
        'cover': json['cover'] === undefined ? undefined : json['cover'] === null ? null : json['cover'],
        'maxPoints': json['maxPoints'] === undefined ? undefined : json['maxPoints'] === null ? null : json['maxPoints'],
        'releaseGrades': json['releaseGrades'] == null ? undefined : json['releaseGrades'],
        'shuffleExercises': json['shuffleExercises'] == null ? undefined : json['shuffleExercises'],
        'submissionStudentsMode': json['submissionStudentsMode'] == null ? undefined : AssignmentSubmissionStudentsModeFromJSON(json['submissionStudentsMode']),
        'recordingType': json['recordingType'] == null ? undefined : json['recordingType'],
        'allowMetronome': json['allowMetronome'] == null ? undefined : json['allowMetronome'],
        'allowBackingTrack': json['allowBackingTrack'] == null ? undefined : json['allowBackingTrack'],
        'allowSpeedChange': json['allowSpeedChange'] == null ? undefined : json['allowSpeedChange'],
        'freeRecord': json['freeRecord'] == null ? undefined : json['freeRecord'],
    };
}

export function AssignmentUpdateToJSON(json: any): AssignmentUpdate {
    return AssignmentUpdateToJSONTyped(json, false);
}

export function AssignmentUpdateToJSONTyped(value?: AssignmentUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': AssignmentTypeToJSON(value['type']),
        'title': value['title'],
        'description': value['description'],
        'descriptionHtml': value['descriptionHtml'],
        'teacherInstructions': value['teacherInstructions'],
        'teacherInstructionsHtml': value['teacherInstructionsHtml'],
        'attachments': value['attachments'] == null ? undefined : ((value['attachments'] as Array<any>).map(ClassAttachmentCreationToJSON)),
        'nbPlaybackAuthorized': value['nbPlaybackAuthorized'],
        'restrictPlayNote': value['restrictPlayNote'],
        'restrictToAudioTracks': value['restrictToAudioTracks'],
        'toolset': value['toolset'],
        'coverFile': value['coverFile'],
        'cover': value['cover'],
        'maxPoints': value['maxPoints'],
        'releaseGrades': value['releaseGrades'],
        'shuffleExercises': value['shuffleExercises'],
        'submissionStudentsMode': AssignmentSubmissionStudentsModeToJSON(value['submissionStudentsMode']),
        'recordingType': value['recordingType'],
        'allowMetronome': value['allowMetronome'],
        'allowBackingTrack': value['allowBackingTrack'],
        'allowSpeedChange': value['allowSpeedChange'],
        'freeRecord': value['freeRecord'],
    };
}

