/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful: it has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference are [available on GitHub](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.2
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Creation of an assignment submission comment
 * @export
 * @interface AssignmentSubmissionCommentCreation
 */
export interface AssignmentSubmissionCommentCreation {
    /**
     * The comment text
     * @type {string}
     * @memberof AssignmentSubmissionCommentCreation
     */
    comment: string;
}

/**
 * Check if a given object implements the AssignmentSubmissionCommentCreation interface.
 */
export function instanceOfAssignmentSubmissionCommentCreation(value: object): value is AssignmentSubmissionCommentCreation {
    if (!('comment' in value) || value['comment'] === undefined) return false;
    return true;
}

export function AssignmentSubmissionCommentCreationFromJSON(json: any): AssignmentSubmissionCommentCreation {
    return AssignmentSubmissionCommentCreationFromJSONTyped(json, false);
}

export function AssignmentSubmissionCommentCreationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignmentSubmissionCommentCreation {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'],
    };
}

export function AssignmentSubmissionCommentCreationToJSON(json: any): AssignmentSubmissionCommentCreation {
    return AssignmentSubmissionCommentCreationToJSONTyped(json, false);
}

export function AssignmentSubmissionCommentCreationToJSONTyped(value?: AssignmentSubmissionCommentCreation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment': value['comment'],
    };
}

