/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful: it has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference are [available on GitHub](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.2
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * State of the submission history
 * @export
 */
export const AssignmentSubmissionHistoryState = {
    Created: 'created',
    TurnedIn: 'turnedIn',
    Returned: 'returned',
    Graded: 'graded',
    Reset: 'reset'
} as const;
export type AssignmentSubmissionHistoryState = typeof AssignmentSubmissionHistoryState[keyof typeof AssignmentSubmissionHistoryState];


export function instanceOfAssignmentSubmissionHistoryState(value: any): boolean {
    for (const key in AssignmentSubmissionHistoryState) {
        if (Object.prototype.hasOwnProperty.call(AssignmentSubmissionHistoryState, key)) {
            if (AssignmentSubmissionHistoryState[key as keyof typeof AssignmentSubmissionHistoryState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AssignmentSubmissionHistoryStateFromJSON(json: any): AssignmentSubmissionHistoryState {
    return AssignmentSubmissionHistoryStateFromJSONTyped(json, false);
}

export function AssignmentSubmissionHistoryStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignmentSubmissionHistoryState {
    return json as AssignmentSubmissionHistoryState;
}

export function AssignmentSubmissionHistoryStateToJSON(value?: AssignmentSubmissionHistoryState | null): any {
    return value as any;
}

export function AssignmentSubmissionHistoryStateToJSONTyped(value: any, ignoreDiscriminator: boolean): AssignmentSubmissionHistoryState {
    return value as AssignmentSubmissionHistoryState;
}

