/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful: it has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference are [available on GitHub](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.2
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ClassGradeLevel } from './ClassGradeLevel.js';
import {
    ClassGradeLevelFromJSON,
    ClassGradeLevelFromJSONTyped,
    ClassGradeLevelToJSON,
    ClassGradeLevelToJSONTyped,
} from './ClassGradeLevel.js';

/**
 * Update of a classroom
 * @export
 * @interface ClassUpdate
 */
export interface ClassUpdate {
    /**
     * The name of the class
     * @type {string}
     * @memberof ClassUpdate
     */
    name?: string;
    /**
     * The section of the class
     * @type {string}
     * @memberof ClassUpdate
     */
    section?: string;
    /**
     * 
     * @type {ClassGradeLevel}
     * @memberof ClassUpdate
     */
    level?: ClassGradeLevel;
    /**
     * Specific skills that will be focused in classroom
     * @type {Array<ClassUpdateSkillsFocusedEnum>}
     * @memberof ClassUpdate
     */
    skillsFocused?: Array<ClassUpdateSkillsFocusedEnum>;
    /**
     * Number of students in the classroom
     * @type {number}
     * @memberof ClassUpdate
     */
    size?: number | null;
}


/**
 * @export
 */
export const ClassUpdateSkillsFocusedEnum = {
    Notation: 'notation',
    SightReading: 'sight-reading',
    PerformanceInstrumental: 'performance-instrumental',
    EarTraining: 'ear-training',
    MusicTheory: 'music-theory',
    Composition: 'composition',
    JazzEnsemble: 'jazz-ensemble',
    MusicTechnology: 'music-technology',
    Other: 'other'
} as const;
export type ClassUpdateSkillsFocusedEnum = typeof ClassUpdateSkillsFocusedEnum[keyof typeof ClassUpdateSkillsFocusedEnum];


/**
 * Check if a given object implements the ClassUpdate interface.
 */
export function instanceOfClassUpdate(value: object): value is ClassUpdate {
    return true;
}

export function ClassUpdateFromJSON(json: any): ClassUpdate {
    return ClassUpdateFromJSONTyped(json, false);
}

export function ClassUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'section': json['section'] == null ? undefined : json['section'],
        'level': json['level'] == null ? undefined : ClassGradeLevelFromJSON(json['level']),
        'skillsFocused': json['skillsFocused'] == null ? undefined : json['skillsFocused'],
        'size': json['size'] === undefined ? undefined : json['size'] === null ? null : json['size'],
    };
}

export function ClassUpdateToJSON(json: any): ClassUpdate {
    return ClassUpdateToJSONTyped(json, false);
}

export function ClassUpdateToJSONTyped(value?: ClassUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'section': value['section'],
        'level': ClassGradeLevelToJSON(value['level']),
        'skillsFocused': value['skillsFocused'],
        'size': value['size'],
    };
}

