/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.1
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ClassDetailsLti } from './ClassDetailsLti.js';
import {
    ClassDetailsLtiFromJSON,
    ClassDetailsLtiFromJSONTyped,
    ClassDetailsLtiToJSON,
    ClassDetailsLtiToJSONTyped,
} from './ClassDetailsLti.js';
import type { ClassState } from './ClassState.js';
import {
    ClassStateFromJSON,
    ClassStateFromJSONTyped,
    ClassStateToJSON,
    ClassStateToJSONTyped,
} from './ClassState.js';
import type { GroupDetails } from './GroupDetails.js';
import {
    GroupDetailsFromJSON,
    GroupDetailsFromJSONTyped,
    GroupDetailsToJSON,
    GroupDetailsToJSONTyped,
} from './GroupDetails.js';
import type { ClassDetailsIssues } from './ClassDetailsIssues.js';
import {
    ClassDetailsIssuesFromJSON,
    ClassDetailsIssuesFromJSONTyped,
    ClassDetailsIssuesToJSON,
    ClassDetailsIssuesToJSONTyped,
} from './ClassDetailsIssues.js';
import type { ClassDetailsCanvas } from './ClassDetailsCanvas.js';
import {
    ClassDetailsCanvasFromJSON,
    ClassDetailsCanvasFromJSONTyped,
    ClassDetailsCanvasToJSON,
    ClassDetailsCanvasToJSONTyped,
} from './ClassDetailsCanvas.js';
import type { ClassDetailsGoogleClassroom } from './ClassDetailsGoogleClassroom.js';
import {
    ClassDetailsGoogleClassroomFromJSON,
    ClassDetailsGoogleClassroomFromJSONTyped,
    ClassDetailsGoogleClassroomToJSON,
    ClassDetailsGoogleClassroomToJSONTyped,
} from './ClassDetailsGoogleClassroom.js';
import type { ClassDetailsMfc } from './ClassDetailsMfc.js';
import {
    ClassDetailsMfcFromJSON,
    ClassDetailsMfcFromJSONTyped,
    ClassDetailsMfcToJSON,
    ClassDetailsMfcToJSONTyped,
} from './ClassDetailsMfc.js';
import type { ClassDetailsClever } from './ClassDetailsClever.js';
import {
    ClassDetailsCleverFromJSON,
    ClassDetailsCleverFromJSONTyped,
    ClassDetailsCleverToJSON,
    ClassDetailsCleverToJSONTyped,
} from './ClassDetailsClever.js';
import type { ClassDetailsGoogleDrive } from './ClassDetailsGoogleDrive.js';
import {
    ClassDetailsGoogleDriveFromJSON,
    ClassDetailsGoogleDriveFromJSONTyped,
    ClassDetailsGoogleDriveToJSON,
    ClassDetailsGoogleDriveToJSONTyped,
} from './ClassDetailsGoogleDrive.js';
import type { ClassDetailsMicrosoftGraph } from './ClassDetailsMicrosoftGraph.js';
import {
    ClassDetailsMicrosoftGraphFromJSON,
    ClassDetailsMicrosoftGraphFromJSONTyped,
    ClassDetailsMicrosoftGraphToJSON,
    ClassDetailsMicrosoftGraphToJSONTyped,
} from './ClassDetailsMicrosoftGraph.js';
import type { ClassGradeLevel } from './ClassGradeLevel.js';
import {
    ClassGradeLevelFromJSON,
    ClassGradeLevelFromJSONTyped,
    ClassGradeLevelToJSON,
    ClassGradeLevelToJSONTyped,
} from './ClassGradeLevel.js';

/**
 * A classroom
 * @export
 * @interface ClassDetails
 */
export interface ClassDetails {
    /**
     * The unique identifier of the class
     * @type {string}
     * @memberof ClassDetails
     */
    id: string;
    /**
     * 
     * @type {ClassState}
     * @memberof ClassDetails
     */
    state: ClassState;
    /**
     * The name of the class
     * @type {string}
     * @memberof ClassDetails
     */
    name: string;
    /**
     * The section of the class
     * @type {string}
     * @memberof ClassDetails
     */
    section?: string;
    /**
     * An optionnal description for this class
     * @type {string}
     * @memberof ClassDetails
     */
    description?: string;
    /**
     * The unique identifier of the Organization owning this class
     * @type {string}
     * @memberof ClassDetails
     */
    organization?: string;
    /**
     * The unique identifier of the User owning this class
     * @type {string}
     * @memberof ClassDetails
     */
    owner?: string;
    /**
     * The date when the class was create
     * @type {Date}
     * @memberof ClassDetails
     */
    creationDate: Date;
    /**
     * The date when the class was last modified
     * @type {Date}
     * @memberof ClassDetails
     */
    modificationDate?: Date;
    /**
     * [Teachers only] The enrollment code that can be used by the students to join the class
     * 
     * @type {string}
     * @memberof ClassDetails
     */
    enrollmentCode?: string;
    /**
     * The theme identifier using in Flat User Interface
     * @type {string}
     * @memberof ClassDetails
     */
    theme?: string;
    /**
     * The number of assignments created in the class
     * @type {number}
     * @memberof ClassDetails
     */
    assignmentsCount?: number;
    /**
     * 
     * @type {GroupDetails}
     * @memberof ClassDetails
     */
    studentsGroup?: GroupDetails;
    /**
     * 
     * @type {GroupDetails}
     * @memberof ClassDetails
     */
    teachersGroup?: GroupDetails;
    /**
     * 
     * @type {ClassDetailsIssues}
     * @memberof ClassDetails
     */
    issues?: ClassDetailsIssues;
    /**
     * 
     * @type {ClassDetailsGoogleClassroom}
     * @memberof ClassDetails
     */
    googleClassroom?: ClassDetailsGoogleClassroom;
    /**
     * 
     * @type {ClassDetailsGoogleDrive}
     * @memberof ClassDetails
     */
    googleDrive?: ClassDetailsGoogleDrive;
    /**
     * 
     * @type {ClassDetailsMicrosoftGraph}
     * @memberof ClassDetails
     */
    microsoftGraph?: ClassDetailsMicrosoftGraph;
    /**
     * 
     * @type {ClassDetailsLti}
     * @memberof ClassDetails
     */
    lti?: ClassDetailsLti;
    /**
     * 
     * @type {ClassDetailsCanvas}
     * @memberof ClassDetails
     */
    canvas?: ClassDetailsCanvas;
    /**
     * 
     * @type {ClassDetailsMfc}
     * @memberof ClassDetails
     */
    mfc?: ClassDetailsMfc;
    /**
     * 
     * @type {ClassDetailsClever}
     * @memberof ClassDetails
     */
    clever?: ClassDetailsClever;
    /**
     * 
     * @type {ClassGradeLevel}
     * @memberof ClassDetails
     */
    level?: ClassGradeLevel;
    /**
     * Specific skills that will be focused in classroom
     * @type {Array<ClassDetailsSkillsFocusedEnum>}
     * @memberof ClassDetails
     */
    skillsFocused?: Array<ClassDetailsSkillsFocusedEnum>;
    /**
     * Number of students in the classroom
     * @type {number}
     * @memberof ClassDetails
     */
    size?: number | null;
}


/**
 * @export
 */
export const ClassDetailsSkillsFocusedEnum = {
    Notation: 'notation',
    SightReading: 'sight-reading',
    PerformanceInstrumental: 'performance-instrumental',
    EarTraining: 'ear-training',
    MusicTheory: 'music-theory',
    Composition: 'composition',
    JazzEnsemble: 'jazz-ensemble',
    MusicTechnology: 'music-technology',
    Other: 'other'
} as const;
export type ClassDetailsSkillsFocusedEnum = typeof ClassDetailsSkillsFocusedEnum[keyof typeof ClassDetailsSkillsFocusedEnum];


/**
 * Check if a given object implements the ClassDetails interface.
 */
export function instanceOfClassDetails(value: object): value is ClassDetails {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('creationDate' in value) || value['creationDate'] === undefined) return false;
    return true;
}

export function ClassDetailsFromJSON(json: any): ClassDetails {
    return ClassDetailsFromJSONTyped(json, false);
}

export function ClassDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'state': ClassStateFromJSON(json['state']),
        'name': json['name'],
        'section': json['section'] == null ? undefined : json['section'],
        'description': json['description'] == null ? undefined : json['description'],
        'organization': json['organization'] == null ? undefined : json['organization'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'creationDate': (new Date(json['creationDate'])),
        'modificationDate': json['modificationDate'] == null ? undefined : (new Date(json['modificationDate'])),
        'enrollmentCode': json['enrollmentCode'] == null ? undefined : json['enrollmentCode'],
        'theme': json['theme'] == null ? undefined : json['theme'],
        'assignmentsCount': json['assignmentsCount'] == null ? undefined : json['assignmentsCount'],
        'studentsGroup': json['studentsGroup'] == null ? undefined : GroupDetailsFromJSON(json['studentsGroup']),
        'teachersGroup': json['teachersGroup'] == null ? undefined : GroupDetailsFromJSON(json['teachersGroup']),
        'issues': json['issues'] == null ? undefined : ClassDetailsIssuesFromJSON(json['issues']),
        'googleClassroom': json['googleClassroom'] == null ? undefined : ClassDetailsGoogleClassroomFromJSON(json['googleClassroom']),
        'googleDrive': json['googleDrive'] == null ? undefined : ClassDetailsGoogleDriveFromJSON(json['googleDrive']),
        'microsoftGraph': json['microsoftGraph'] == null ? undefined : ClassDetailsMicrosoftGraphFromJSON(json['microsoftGraph']),
        'lti': json['lti'] == null ? undefined : ClassDetailsLtiFromJSON(json['lti']),
        'canvas': json['canvas'] == null ? undefined : ClassDetailsCanvasFromJSON(json['canvas']),
        'mfc': json['mfc'] == null ? undefined : ClassDetailsMfcFromJSON(json['mfc']),
        'clever': json['clever'] == null ? undefined : ClassDetailsCleverFromJSON(json['clever']),
        'level': json['level'] == null ? undefined : ClassGradeLevelFromJSON(json['level']),
        'skillsFocused': json['skillsFocused'] == null ? undefined : json['skillsFocused'],
        'size': json['size'] === undefined ? undefined : json['size'] === null ? null : json['size'],
    };
}

export function ClassDetailsToJSON(json: any): ClassDetails {
    return ClassDetailsToJSONTyped(json, false);
}

export function ClassDetailsToJSONTyped(value?: ClassDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'state': ClassStateToJSON(value['state']),
        'name': value['name'],
        'section': value['section'],
        'description': value['description'],
        'organization': value['organization'],
        'owner': value['owner'],
        'creationDate': value['creationDate'].toISOString(),
        'modificationDate': value['modificationDate'] == null ? value['modificationDate'] : value['modificationDate'].toISOString(),
        'enrollmentCode': value['enrollmentCode'],
        'theme': value['theme'],
        'assignmentsCount': value['assignmentsCount'],
        'studentsGroup': GroupDetailsToJSON(value['studentsGroup']),
        'teachersGroup': GroupDetailsToJSON(value['teachersGroup']),
        'issues': ClassDetailsIssuesToJSON(value['issues']),
        'googleClassroom': ClassDetailsGoogleClassroomToJSON(value['googleClassroom']),
        'googleDrive': ClassDetailsGoogleDriveToJSON(value['googleDrive']),
        'microsoftGraph': ClassDetailsMicrosoftGraphToJSON(value['microsoftGraph']),
        'lti': ClassDetailsLtiToJSON(value['lti']),
        'canvas': ClassDetailsCanvasToJSON(value['canvas']),
        'mfc': ClassDetailsMfcToJSON(value['mfc']),
        'clever': ClassDetailsCleverToJSON(value['clever']),
        'level': ClassGradeLevelToJSON(value['level']),
        'skillsFocused': value['skillsFocused'],
        'size': value['size'],
    };
}

