/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful: it has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference are [available on GitHub](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.2
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of the collection.
 * The type will influence the capabilities available on the collections and how this collection is/can be populated.
 * 
 * - `root`: **Deprecated.** Previously the root collection of the user. The `allScores` virtual collection should be used instead.
 * - `regular`: A regular collection created by the user. This collection can be deleted and modified by the user.
 * - `app`: An automatically created collection containing the scores created by an app (e.g. Music Snippet)
 * - `trash`: An automatically created collection containing the trashed scores.
 * 
 * Virtual collections:
 * 
 * - `allScores`: All the scores contained in the user account
 * - `collaborations`: All shared scores by the user or someone else
 * - `likes`: Liked scores
 * 
 * @export
 */
export const CollectionType = {
    Root: 'root',
    Regular: 'regular',
    App: 'app',
    Trash: 'trash',
    AllScores: 'allScores',
    Collaborations: 'collaborations',
    Likes: 'likes'
} as const;
export type CollectionType = typeof CollectionType[keyof typeof CollectionType];


export function instanceOfCollectionType(value: any): boolean {
    for (const key in CollectionType) {
        if (Object.prototype.hasOwnProperty.call(CollectionType, key)) {
            if (CollectionType[key as keyof typeof CollectionType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CollectionTypeFromJSON(json: any): CollectionType {
    return CollectionTypeFromJSONTyped(json, false);
}

export function CollectionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionType {
    return json as CollectionType;
}

export function CollectionTypeToJSON(value?: CollectionType | null): any {
    return value as any;
}

export function CollectionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CollectionType {
    return value as CollectionType;
}

