/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful: it has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference are [available on GitHub](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.2
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * LMS name
 * @export
 */
export const LmsName = {
    Canvas: 'canvas',
    Moodle: 'moodle',
    Schoology: 'schoology',
    Blackboard: 'blackboard',
    Desire2learn: 'desire2learn',
    Sakai: 'sakai',
    Schoolbox: 'schoolbox',
    Other: 'other'
} as const;
export type LmsName = typeof LmsName[keyof typeof LmsName];


export function instanceOfLmsName(value: any): boolean {
    for (const key in LmsName) {
        if (Object.prototype.hasOwnProperty.call(LmsName, key)) {
            if (LmsName[key as keyof typeof LmsName] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LmsNameFromJSON(json: any): LmsName {
    return LmsNameFromJSONTyped(json, false);
}

export function LmsNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): LmsName {
    return json as LmsName;
}

export function LmsNameToJSON(value?: LmsName | null): any {
    return value as any;
}

export function LmsNameToJSONTyped(value: any, ignoreDiscriminator: boolean): LmsName {
    return value as LmsName;
}

