/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.1
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { LtiConfiguration1p1 } from './LtiConfiguration1p1.js';
import {
    LtiConfiguration1p1FromJSON,
    LtiConfiguration1p1FromJSONTyped,
    LtiConfiguration1p1ToJSON,
} from './LtiConfiguration1p1.js';
import type { LtiConfiguration1p3 } from './LtiConfiguration1p3.js';
import {
    LtiConfiguration1p3FromJSON,
    LtiConfiguration1p3FromJSONTyped,
    LtiConfiguration1p3ToJSON,
} from './LtiConfiguration1p3.js';

/**
 * @type LtiConfiguration
 * LTI configuration details (unified 1.1 and 1.3)
 * @export
 */
export type LtiConfiguration = { ltiVersion: '1p1' } & LtiConfiguration1p1 | { ltiVersion: '1p3' } & LtiConfiguration1p3;

export function LtiConfigurationFromJSON(json: any): LtiConfiguration {
    return LtiConfigurationFromJSONTyped(json, false);
}

export function LtiConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): LtiConfiguration {
    if (json == null) {
        return json;
    }
    switch (json['ltiVersion']) {
        case '1p1':
            return Object.assign({}, LtiConfiguration1p1FromJSONTyped(json, true), { ltiVersion: '1p1' } as const);
        case '1p3':
            return Object.assign({}, LtiConfiguration1p3FromJSONTyped(json, true), { ltiVersion: '1p3' } as const);
        default:
            return json;
    }
}

export function LtiConfigurationToJSON(json: any): any {
    return LtiConfigurationToJSONTyped(json, false);
}

export function LtiConfigurationToJSONTyped(value?: LtiConfiguration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['ltiVersion']) {
        case '1p1':
            return Object.assign({}, LtiConfiguration1p1ToJSON(value), { 'ltiVersion': '1p1' } as const);
        case '1p3':
            return Object.assign({}, LtiConfiguration1p3ToJSON(value), { 'ltiVersion': '1p3' } as const);
        default:
            return value;
    }
}

