/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful: it has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference are [available on GitHub](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.2
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { LtiConfiguration1p3BaseSupportedServices } from './LtiConfiguration1p3BaseSupportedServices.js';
import {
    LtiConfiguration1p3BaseSupportedServicesFromJSON,
    LtiConfiguration1p3BaseSupportedServicesFromJSONTyped,
    LtiConfiguration1p3BaseSupportedServicesToJSON,
    LtiConfiguration1p3BaseSupportedServicesToJSONTyped,
} from './LtiConfiguration1p3BaseSupportedServices.js';
import type { LtiConfiguration1p3BaseTool } from './LtiConfiguration1p3BaseTool.js';
import {
    LtiConfiguration1p3BaseToolFromJSON,
    LtiConfiguration1p3BaseToolFromJSONTyped,
    LtiConfiguration1p3BaseToolToJSON,
    LtiConfiguration1p3BaseToolToJSONTyped,
} from './LtiConfiguration1p3BaseTool.js';

/**
 * 
 * @export
 * @interface LtiConfiguration1p3Manual
 */
export interface LtiConfiguration1p3Manual {
    /**
     * Configuration ID
     * @type {string}
     * @memberof LtiConfiguration1p3Manual
     */
    id: string;
    /**
     * LTI version (1.3)
     * @type {LtiConfiguration1p3ManualLtiVersionEnum}
     * @memberof LtiConfiguration1p3Manual
     */
    ltiVersion: LtiConfiguration1p3ManualLtiVersionEnum;
    /**
     * Organization ID
     * @type {string}
     * @memberof LtiConfiguration1p3Manual
     */
    organizationId?: string;
    /**
     * Organization name
     * @type {string}
     * @memberof LtiConfiguration1p3Manual
     */
    organizationName?: string;
    /**
     * ID of the user who created this configuration
     * @type {string}
     * @memberof LtiConfiguration1p3Manual
     */
    creatorId?: string;
    /**
     * Configuration creation date
     * @type {Date}
     * @memberof LtiConfiguration1p3Manual
     */
    creationDate: Date;
    /**
     * Last time this configuration was used
     * @type {Date}
     * @memberof LtiConfiguration1p3Manual
     */
    lastUsedDate?: Date;
    /**
     * Configuration status indicator
     * @type {LtiConfiguration1p3ManualStatusEnum}
     * @memberof LtiConfiguration1p3Manual
     */
    status?: LtiConfiguration1p3ManualStatusEnum;
    /**
     * Manual LTI 1.3 configuration mode
     * @type {LtiConfiguration1p3ManualModeEnum}
     * @memberof LtiConfiguration1p3Manual
     */
    mode?: LtiConfiguration1p3ManualModeEnum;
    /**
     * Platform issuer URL
     * @type {string}
     * @memberof LtiConfiguration1p3Manual
     */
    platformIss?: string;
    /**
     * Platform display name
     * @type {string}
     * @memberof LtiConfiguration1p3Manual
     */
    platformName?: string;
    /**
     * OAuth2 client_id allocated by the platform
     * @type {string}
     * @memberof LtiConfiguration1p3Manual
     */
    clientId?: string;
    /**
     * Deployment ID linking the tool to a tenant/class (varies by platform)
     * @type {string}
     * @memberof LtiConfiguration1p3Manual
     */
    deploymentId?: string;
    /**
     * OAuth2 token endpoint (for AGS/NRPS)
     * @type {string}
     * @memberof LtiConfiguration1p3Manual
     */
    accessTokenUrl?: string;
    /**
     * OIDC authorization/login endpoint
     * @type {string}
     * @memberof LtiConfiguration1p3Manual
     */
    authorizationUrl?: string;
    /**
     * Platform JWKS endpoint (public keys)
     * @type {string}
     * @memberof LtiConfiguration1p3Manual
     */
    jwksUrl?: string;
    /**
     * Deployment mode (single for organization-specific, multi for shared parent platforms)
     * @type {LtiConfiguration1p3ManualDeploymentModeEnum}
     * @memberof LtiConfiguration1p3Manual
     */
    deploymentMode?: LtiConfiguration1p3ManualDeploymentModeEnum;
    /**
     * 
     * @type {LtiConfiguration1p3BaseSupportedServices}
     * @memberof LtiConfiguration1p3Manual
     */
    supportedServices?: LtiConfiguration1p3BaseSupportedServices;
    /**
     * 
     * @type {LtiConfiguration1p3BaseTool}
     * @memberof LtiConfiguration1p3Manual
     */
    tool?: LtiConfiguration1p3BaseTool;
    /**
     * Public keyset URL for the platform to retrieve Flat's public keys
     * @type {string}
     * @memberof LtiConfiguration1p3Manual
     */
    publicKeysetUrl?: string;
    /**
     * URL for the platform to initiate LTI login
     * @type {string}
     * @memberof LtiConfiguration1p3Manual
     */
    initiateLoginUrl?: string;
    /**
     * Allowed redirect URIs for LTI launches
     * @type {Array<string>}
     * @memberof LtiConfiguration1p3Manual
     */
    redirectUris?: Array<string>;
    /**
     * Enable email-based user matching during LTI authentication.
     * 
     * When true (default): If a user with the same email exists in the organization,
     * they will be matched and logged in instead of creating a new account.
     * 
     * When false: Email matching is disabled. Only LTI ID matching is used, which means
     * multiple LTI users can share the same email address and have separate Flat accounts.
     * This is useful for cases like siblings sharing a parent email in the LMS.
     * 
     * @type {boolean}
     * @memberof LtiConfiguration1p3Manual
     */
    enableEmailMatching?: boolean;
}


/**
 * @export
 */
export const LtiConfiguration1p3ManualLtiVersionEnum = {
    _1p3: '1p3'
} as const;
export type LtiConfiguration1p3ManualLtiVersionEnum = typeof LtiConfiguration1p3ManualLtiVersionEnum[keyof typeof LtiConfiguration1p3ManualLtiVersionEnum];

/**
 * @export
 */
export const LtiConfiguration1p3ManualStatusEnum = {
    ReadyToUse: 'ready-to-use',
    InUse: 'in-use',
    IncompleteSetup: 'incomplete-setup'
} as const;
export type LtiConfiguration1p3ManualStatusEnum = typeof LtiConfiguration1p3ManualStatusEnum[keyof typeof LtiConfiguration1p3ManualStatusEnum];

/**
 * @export
 */
export const LtiConfiguration1p3ManualModeEnum = {
    _1p3Manual: '1p3-manual'
} as const;
export type LtiConfiguration1p3ManualModeEnum = typeof LtiConfiguration1p3ManualModeEnum[keyof typeof LtiConfiguration1p3ManualModeEnum];

/**
 * @export
 */
export const LtiConfiguration1p3ManualDeploymentModeEnum = {
    Single: 'single',
    Multi: 'multi'
} as const;
export type LtiConfiguration1p3ManualDeploymentModeEnum = typeof LtiConfiguration1p3ManualDeploymentModeEnum[keyof typeof LtiConfiguration1p3ManualDeploymentModeEnum];


/**
 * Check if a given object implements the LtiConfiguration1p3Manual interface.
 */
export function instanceOfLtiConfiguration1p3Manual(value: object): value is LtiConfiguration1p3Manual {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ltiVersion' in value) || value['ltiVersion'] === undefined) return false;
    if (value['ltiVersion'] !== '1p3') return false;
    
    if (!('creationDate' in value) || value['creationDate'] === undefined) return false;
    return true;
}

export function LtiConfiguration1p3ManualFromJSON(json: any): LtiConfiguration1p3Manual {
    return LtiConfiguration1p3ManualFromJSONTyped(json, false);
}

export function LtiConfiguration1p3ManualFromJSONTyped(json: any, ignoreDiscriminator: boolean): LtiConfiguration1p3Manual {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ltiVersion': json['ltiVersion'],
        'organizationId': json['organizationId'] == null ? undefined : json['organizationId'],
        'organizationName': json['organizationName'] == null ? undefined : json['organizationName'],
        'creatorId': json['creatorId'] == null ? undefined : json['creatorId'],
        'creationDate': (new Date(json['creationDate'])),
        'lastUsedDate': json['lastUsedDate'] == null ? undefined : (new Date(json['lastUsedDate'])),
        'status': json['status'] == null ? undefined : json['status'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'platformIss': json['platformIss'] == null ? undefined : json['platformIss'],
        'platformName': json['platformName'] == null ? undefined : json['platformName'],
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
        'deploymentId': json['deploymentId'] == null ? undefined : json['deploymentId'],
        'accessTokenUrl': json['accessTokenUrl'] == null ? undefined : json['accessTokenUrl'],
        'authorizationUrl': json['authorizationUrl'] == null ? undefined : json['authorizationUrl'],
        'jwksUrl': json['jwksUrl'] == null ? undefined : json['jwksUrl'],
        'deploymentMode': json['deploymentMode'] == null ? undefined : json['deploymentMode'],
        'supportedServices': json['supportedServices'] == null ? undefined : LtiConfiguration1p3BaseSupportedServicesFromJSON(json['supportedServices']),
        'tool': json['tool'] == null ? undefined : LtiConfiguration1p3BaseToolFromJSON(json['tool']),
        'publicKeysetUrl': json['publicKeysetUrl'] == null ? undefined : json['publicKeysetUrl'],
        'initiateLoginUrl': json['initiateLoginUrl'] == null ? undefined : json['initiateLoginUrl'],
        'redirectUris': json['redirectUris'] == null ? undefined : json['redirectUris'],
        'enableEmailMatching': json['enableEmailMatching'] == null ? undefined : json['enableEmailMatching'],
    };
}

export function LtiConfiguration1p3ManualToJSON(json: any): LtiConfiguration1p3Manual {
    return LtiConfiguration1p3ManualToJSONTyped(json, false);
}

export function LtiConfiguration1p3ManualToJSONTyped(value?: LtiConfiguration1p3Manual | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ltiVersion': value['ltiVersion'],
        'organizationId': value['organizationId'],
        'organizationName': value['organizationName'],
        'creatorId': value['creatorId'],
        'creationDate': value['creationDate'].toISOString(),
        'lastUsedDate': value['lastUsedDate'] == null ? value['lastUsedDate'] : value['lastUsedDate'].toISOString(),
        'status': value['status'],
        'mode': value['mode'],
        'platformIss': value['platformIss'],
        'platformName': value['platformName'],
        'clientId': value['clientId'],
        'deploymentId': value['deploymentId'],
        'accessTokenUrl': value['accessTokenUrl'],
        'authorizationUrl': value['authorizationUrl'],
        'jwksUrl': value['jwksUrl'],
        'deploymentMode': value['deploymentMode'],
        'supportedServices': LtiConfiguration1p3BaseSupportedServicesToJSON(value['supportedServices']),
        'tool': LtiConfiguration1p3BaseToolToJSON(value['tool']),
        'publicKeysetUrl': value['publicKeysetUrl'],
        'initiateLoginUrl': value['initiateLoginUrl'],
        'redirectUris': value['redirectUris'],
        'enableEmailMatching': value['enableEmailMatching'],
    };
}

