/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful: it has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference are [available on GitHub](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.2
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Platform/tool product information
 * @export
 * @interface LtiConfiguration1p3BaseTool
 */
export interface LtiConfiguration1p3BaseTool {
    /**
     * Product family code (e.g., canvas, moodle, schoology)
     * @type {string}
     * @memberof LtiConfiguration1p3BaseTool
     */
    product?: string;
    /**
     * Platform version string
     * @type {string}
     * @memberof LtiConfiguration1p3BaseTool
     */
    version?: string;
    /**
     * Instance name (e.g., 'My University Canvas')
     * @type {string}
     * @memberof LtiConfiguration1p3BaseTool
     */
    instanceName?: string;
    /**
     * Unique instance identifier
     * @type {string}
     * @memberof LtiConfiguration1p3BaseTool
     */
    instanceGuid?: string;
    /**
     * Contact email or handle for the instance
     * @type {string}
     * @memberof LtiConfiguration1p3BaseTool
     */
    instanceContact?: string;
    /**
     * Instance root domain
     * @type {string}
     * @memberof LtiConfiguration1p3BaseTool
     */
    instanceDomain?: string;
}

/**
 * Check if a given object implements the LtiConfiguration1p3BaseTool interface.
 */
export function instanceOfLtiConfiguration1p3BaseTool(value: object): value is LtiConfiguration1p3BaseTool {
    return true;
}

export function LtiConfiguration1p3BaseToolFromJSON(json: any): LtiConfiguration1p3BaseTool {
    return LtiConfiguration1p3BaseToolFromJSONTyped(json, false);
}

export function LtiConfiguration1p3BaseToolFromJSONTyped(json: any, ignoreDiscriminator: boolean): LtiConfiguration1p3BaseTool {
    if (json == null) {
        return json;
    }
    return {
        
        'product': json['product'] == null ? undefined : json['product'],
        'version': json['version'] == null ? undefined : json['version'],
        'instanceName': json['instanceName'] == null ? undefined : json['instanceName'],
        'instanceGuid': json['instanceGuid'] == null ? undefined : json['instanceGuid'],
        'instanceContact': json['instanceContact'] == null ? undefined : json['instanceContact'],
        'instanceDomain': json['instanceDomain'] == null ? undefined : json['instanceDomain'],
    };
}

export function LtiConfiguration1p3BaseToolToJSON(json: any): LtiConfiguration1p3BaseTool {
    return LtiConfiguration1p3BaseToolToJSONTyped(json, false);
}

export function LtiConfiguration1p3BaseToolToJSONTyped(value?: LtiConfiguration1p3BaseTool | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'product': value['product'],
        'version': value['version'],
        'instanceName': value['instanceName'],
        'instanceGuid': value['instanceGuid'],
        'instanceContact': value['instanceContact'],
        'instanceDomain': value['instanceDomain'],
    };
}

