/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful: it has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference are [available on GitHub](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.2
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { LtiConfiguration1p3BaseSupportedServicesNrps } from './LtiConfiguration1p3BaseSupportedServicesNrps.js';
import {
    LtiConfiguration1p3BaseSupportedServicesNrpsFromJSON,
    LtiConfiguration1p3BaseSupportedServicesNrpsFromJSONTyped,
    LtiConfiguration1p3BaseSupportedServicesNrpsToJSON,
    LtiConfiguration1p3BaseSupportedServicesNrpsToJSONTyped,
} from './LtiConfiguration1p3BaseSupportedServicesNrps.js';
import type { LtiConfiguration1p3BaseSupportedServicesAgs } from './LtiConfiguration1p3BaseSupportedServicesAgs.js';
import {
    LtiConfiguration1p3BaseSupportedServicesAgsFromJSON,
    LtiConfiguration1p3BaseSupportedServicesAgsFromJSONTyped,
    LtiConfiguration1p3BaseSupportedServicesAgsToJSON,
    LtiConfiguration1p3BaseSupportedServicesAgsToJSONTyped,
} from './LtiConfiguration1p3BaseSupportedServicesAgs.js';
import type { LtiConfiguration1p3BaseSupportedServicesDeepLinking } from './LtiConfiguration1p3BaseSupportedServicesDeepLinking.js';
import {
    LtiConfiguration1p3BaseSupportedServicesDeepLinkingFromJSON,
    LtiConfiguration1p3BaseSupportedServicesDeepLinkingFromJSONTyped,
    LtiConfiguration1p3BaseSupportedServicesDeepLinkingToJSON,
    LtiConfiguration1p3BaseSupportedServicesDeepLinkingToJSONTyped,
} from './LtiConfiguration1p3BaseSupportedServicesDeepLinking.js';

/**
 * LTI services support information
 * @export
 * @interface LtiConfiguration1p3BaseSupportedServices
 */
export interface LtiConfiguration1p3BaseSupportedServices {
    /**
     * 
     * @type {LtiConfiguration1p3BaseSupportedServicesAgs}
     * @memberof LtiConfiguration1p3BaseSupportedServices
     */
    ags?: LtiConfiguration1p3BaseSupportedServicesAgs;
    /**
     * 
     * @type {LtiConfiguration1p3BaseSupportedServicesNrps}
     * @memberof LtiConfiguration1p3BaseSupportedServices
     */
    nrps?: LtiConfiguration1p3BaseSupportedServicesNrps;
    /**
     * 
     * @type {LtiConfiguration1p3BaseSupportedServicesDeepLinking}
     * @memberof LtiConfiguration1p3BaseSupportedServices
     */
    deepLinking?: LtiConfiguration1p3BaseSupportedServicesDeepLinking;
}

/**
 * Check if a given object implements the LtiConfiguration1p3BaseSupportedServices interface.
 */
export function instanceOfLtiConfiguration1p3BaseSupportedServices(value: object): value is LtiConfiguration1p3BaseSupportedServices {
    return true;
}

export function LtiConfiguration1p3BaseSupportedServicesFromJSON(json: any): LtiConfiguration1p3BaseSupportedServices {
    return LtiConfiguration1p3BaseSupportedServicesFromJSONTyped(json, false);
}

export function LtiConfiguration1p3BaseSupportedServicesFromJSONTyped(json: any, ignoreDiscriminator: boolean): LtiConfiguration1p3BaseSupportedServices {
    if (json == null) {
        return json;
    }
    return {
        
        'ags': json['ags'] == null ? undefined : LtiConfiguration1p3BaseSupportedServicesAgsFromJSON(json['ags']),
        'nrps': json['nrps'] == null ? undefined : LtiConfiguration1p3BaseSupportedServicesNrpsFromJSON(json['nrps']),
        'deepLinking': json['deepLinking'] == null ? undefined : LtiConfiguration1p3BaseSupportedServicesDeepLinkingFromJSON(json['deepLinking']),
    };
}

export function LtiConfiguration1p3BaseSupportedServicesToJSON(json: any): LtiConfiguration1p3BaseSupportedServices {
    return LtiConfiguration1p3BaseSupportedServicesToJSONTyped(json, false);
}

export function LtiConfiguration1p3BaseSupportedServicesToJSONTyped(value?: LtiConfiguration1p3BaseSupportedServices | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ags': LtiConfiguration1p3BaseSupportedServicesAgsToJSON(value['ags']),
        'nrps': LtiConfiguration1p3BaseSupportedServicesNrpsToJSON(value['nrps']),
        'deepLinking': LtiConfiguration1p3BaseSupportedServicesDeepLinkingToJSON(value['deepLinking']),
    };
}

