/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful: it has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference are [available on GitHub](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.2
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { LmsName } from './LmsName.js';
import {
    LmsNameFromJSON,
    LmsNameFromJSONTyped,
    LmsNameToJSON,
    LmsNameToJSONTyped,
} from './LmsName.js';

/**
 * A pair of LTI 1.1 OAuth credentials
 * @export
 * @interface LtiCredentials
 */
export interface LtiCredentials {
    /**
     * The unique identifier of this pair of credentials
     * @type {string}
     * @memberof LtiCredentials
     */
    id?: string;
    /**
     * Name of the pair of credentials
     * @type {string}
     * @memberof LtiCredentials
     */
    name?: string;
    /**
     * 
     * @type {LmsName}
     * @memberof LtiCredentials
     */
    lms?: LmsName;
    /**
     * The unique identifier of the Organization associated to these credentials
     * @type {string}
     * @memberof LtiCredentials
     */
    organization?: string;
    /**
     * Unique identifier of the user who created these credentials
     * @type {string}
     * @memberof LtiCredentials
     */
    creator?: string;
    /**
     * The creation date of these credentials
     * @type {Date}
     * @memberof LtiCredentials
     */
    creationDate?: Date;
    /**
     * The last time these credentials were used
     * @type {Date}
     * @memberof LtiCredentials
     */
    lastUsage?: Date;
    /**
     * OAuth 1 Consumer Key
     * @type {string}
     * @memberof LtiCredentials
     */
    consumerKey?: string;
    /**
     * OAuth 1 Consumer Secret
     * @type {string}
     * @memberof LtiCredentials
     */
    consumerSecret?: string;
    /**
     * Enable email-based user matching during LTI authentication.
     * 
     * When true (default): If a user with the same email exists in the organization,
     * they will be matched and logged in instead of creating a new account.
     * 
     * When false: Email matching is disabled. Only LTI ID matching is used, which means
     * multiple LTI users can share the same email address and have separate Flat accounts.
     * This is useful for cases like siblings sharing a parent email in the LMS.
     * 
     * @type {boolean}
     * @memberof LtiCredentials
     */
    enableEmailMatching?: boolean;
}



/**
 * Check if a given object implements the LtiCredentials interface.
 */
export function instanceOfLtiCredentials(value: object): value is LtiCredentials {
    return true;
}

export function LtiCredentialsFromJSON(json: any): LtiCredentials {
    return LtiCredentialsFromJSONTyped(json, false);
}

export function LtiCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LtiCredentials {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'lms': json['lms'] == null ? undefined : LmsNameFromJSON(json['lms']),
        'organization': json['organization'] == null ? undefined : json['organization'],
        'creator': json['creator'] == null ? undefined : json['creator'],
        'creationDate': json['creationDate'] == null ? undefined : (new Date(json['creationDate'])),
        'lastUsage': json['lastUsage'] == null ? undefined : (new Date(json['lastUsage'])),
        'consumerKey': json['consumerKey'] == null ? undefined : json['consumerKey'],
        'consumerSecret': json['consumerSecret'] == null ? undefined : json['consumerSecret'],
        'enableEmailMatching': json['enableEmailMatching'] == null ? undefined : json['enableEmailMatching'],
    };
}

export function LtiCredentialsToJSON(json: any): LtiCredentials {
    return LtiCredentialsToJSONTyped(json, false);
}

export function LtiCredentialsToJSONTyped(value?: LtiCredentials | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'lms': LmsNameToJSON(value['lms']),
        'organization': value['organization'],
        'creator': value['creator'],
        'creationDate': value['creationDate'] == null ? value['creationDate'] : value['creationDate'].toISOString(),
        'lastUsage': value['lastUsage'] == null ? value['lastUsage'] : value['lastUsage'].toISOString(),
        'consumerKey': value['consumerKey'],
        'consumerSecret': value['consumerSecret'],
        'enableEmailMatching': value['enableEmailMatching'],
    };
}

