/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.1
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { OmrInstrumentOverride } from './OmrInstrumentOverride.js';
import {
    OmrInstrumentOverrideFromJSON,
    OmrInstrumentOverrideFromJSONTyped,
    OmrInstrumentOverrideToJSON,
    OmrInstrumentOverrideToJSONTyped,
} from './OmrInstrumentOverride.js';

/**
 * Overrides for the `details` step. Omitted fields keep the server's detected values.
 * @export
 * @interface OmrDetailsSubmission
 */
export interface OmrDetailsSubmission {
    /**
     * Discriminator for `OmrStepSubmission`; always `details` for this submission.
     * @type {OmrDetailsSubmissionStepEnum}
     * @memberof OmrDetailsSubmission
     */
    step: OmrDetailsSubmissionStepEnum;
    /**
     * Override the detected work title.
     * @type {string}
     * @memberof OmrDetailsSubmission
     */
    title?: string;
    /**
     * Override the main language (BCP 47) used for lyric and text reading on resume.
     * Defaults to the job locale (`locales`); set this to correct it on the review screen.
     * 
     * @type {string}
     * @memberof OmrDetailsSubmission
     */
    mainLanguage?: string;
    /**
     * Per-part overrides, each matched to a detected part by `index`.
     * @type {Array<OmrInstrumentOverride>}
     * @memberof OmrDetailsSubmission
     */
    instruments?: Array<OmrInstrumentOverride>;
}


/**
 * @export
 */
export const OmrDetailsSubmissionStepEnum = {
    Details: 'details'
} as const;
export type OmrDetailsSubmissionStepEnum = typeof OmrDetailsSubmissionStepEnum[keyof typeof OmrDetailsSubmissionStepEnum];


/**
 * Check if a given object implements the OmrDetailsSubmission interface.
 */
export function instanceOfOmrDetailsSubmission(value: object): value is OmrDetailsSubmission {
    if (!('step' in value) || value['step'] === undefined) return false;
    if (value['step'] !== 'details') return false;
    
    return true;
}

export function OmrDetailsSubmissionFromJSON(json: any): OmrDetailsSubmission {
    return OmrDetailsSubmissionFromJSONTyped(json, false);
}

export function OmrDetailsSubmissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): OmrDetailsSubmission {
    if (json == null) {
        return json;
    }
    return {
        
        'step': json['step'],
        'title': json['title'] == null ? undefined : json['title'],
        'mainLanguage': json['mainLanguage'] == null ? undefined : json['mainLanguage'],
        'instruments': json['instruments'] == null ? undefined : ((json['instruments'] as Array<any>).map(OmrInstrumentOverrideFromJSON)),
    };
}

export function OmrDetailsSubmissionToJSON(json: any): OmrDetailsSubmission {
    return OmrDetailsSubmissionToJSONTyped(json, false);
}

export function OmrDetailsSubmissionToJSONTyped(value?: OmrDetailsSubmission | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'step': value['step'],
        'title': value['title'],
        'mainLanguage': value['mainLanguage'],
        'instruments': value['instruments'] == null ? undefined : ((value['instruments'] as Array<any>).map(OmrInstrumentOverrideToJSON)),
    };
}

