/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.1
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Result of adding a file to a draft job.
 * @export
 * @interface OmrJobFileUploadResult
 */
export interface OmrJobFileUploadResult {
    /**
     * 0-based index assigned to the uploaded file.
     * @type {number}
     * @memberof OmrJobFileUploadResult
     */
    fileIndex?: number;
    /**
     * Total number of files now attached to the job.
     * @type {number}
     * @memberof OmrJobFileUploadResult
     */
    fileCount?: number;
}

/**
 * Check if a given object implements the OmrJobFileUploadResult interface.
 */
export function instanceOfOmrJobFileUploadResult(value: object): value is OmrJobFileUploadResult {
    return true;
}

export function OmrJobFileUploadResultFromJSON(json: any): OmrJobFileUploadResult {
    return OmrJobFileUploadResultFromJSONTyped(json, false);
}

export function OmrJobFileUploadResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): OmrJobFileUploadResult {
    if (json == null) {
        return json;
    }
    return {
        
        'fileIndex': json['fileIndex'] == null ? undefined : json['fileIndex'],
        'fileCount': json['fileCount'] == null ? undefined : json['fileCount'],
    };
}

export function OmrJobFileUploadResultToJSON(json: any): OmrJobFileUploadResult {
    return OmrJobFileUploadResultToJSONTyped(json, false);
}

export function OmrJobFileUploadResultToJSONTyped(value?: OmrJobFileUploadResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileIndex': value['fileIndex'],
        'fileCount': value['fileCount'],
    };
}

