/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.1
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * The outcome of a finished job. Present when `status` is `done`.
 * @export
 * @interface OmrJobResult
 */
export interface OmrJobResult {
    /**
     * Created score ID, when `output` is `library`.
     * @type {string}
     * @memberof OmrJobResult
     */
    score?: string;
    /**
     * Formats available via `getOmrJobExport`, for example `["musicxml", "mxl", "midi"]`.
     * @type {Array<string>}
     * @memberof OmrJobResult
     */
    exports?: Array<string>;
}

/**
 * Check if a given object implements the OmrJobResult interface.
 */
export function instanceOfOmrJobResult(value: object): value is OmrJobResult {
    return true;
}

export function OmrJobResultFromJSON(json: any): OmrJobResult {
    return OmrJobResultFromJSONTyped(json, false);
}

export function OmrJobResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): OmrJobResult {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'] == null ? undefined : json['score'],
        'exports': json['exports'] == null ? undefined : json['exports'],
    };
}

export function OmrJobResultToJSON(json: any): OmrJobResult {
    return OmrJobResultToJSONTyped(json, false);
}

export function OmrJobResultToJSONTyped(value?: OmrJobResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': value['score'],
        'exports': value['exports'],
    };
}

