/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.1
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Options to fork the score
 * @export
 * @interface ScoreFork
 */
export interface ScoreFork {
    /**
     * Unique identifier of a collection where the score will be copied.
     * 
     * If no collection identifier is provided, a virtual collection is used, or `null` is provided, the score won't be added to any collection and will only be visible in the `allScores` virtual collection.
     * 
     * @type {string}
     * @memberof ScoreFork
     */
    collection?: string | null;
    /**
     * If set to `true`, the API won't create the score on Google Drive
     * 
     * @type {boolean}
     * @memberof ScoreFork
     */
    googleDriveDisabled?: boolean;
    /**
     * Option to keep the original title of the score (i.e. don't prepend it with "Copy of ", or add the student name in assignment usage).
     * 
     * @type {boolean}
     * @memberof ScoreFork
     */
    keepOriginalTitle?: boolean;
}

/**
 * Check if a given object implements the ScoreFork interface.
 */
export function instanceOfScoreFork(value: object): value is ScoreFork {
    return true;
}

export function ScoreForkFromJSON(json: any): ScoreFork {
    return ScoreForkFromJSONTyped(json, false);
}

export function ScoreForkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreFork {
    if (json == null) {
        return json;
    }
    return {
        
        'collection': json['collection'] === undefined ? undefined : json['collection'] === null ? null : json['collection'],
        'googleDriveDisabled': json['googleDriveDisabled'] == null ? undefined : json['googleDriveDisabled'],
        'keepOriginalTitle': json['keepOriginalTitle'] == null ? undefined : json['keepOriginalTitle'],
    };
}

export function ScoreForkToJSON(json: any): ScoreFork {
    return ScoreForkToJSONTyped(json, false);
}

export function ScoreForkToJSONTyped(value?: ScoreFork | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection': value['collection'],
        'googleDriveDisabled': value['googleDriveDisabled'],
        'keepOriginalTitle': value['keepOriginalTitle'],
    };
}

