/* tslint:disable */
/* eslint-disable */
/**
 * Flat API
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user\'s scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat\'s API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 
 *
 * The version of the OpenAPI document: 2.26.1
 * Contact: developers@flat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { OrganizationRoles } from './OrganizationRoles.js';
import {
    OrganizationRolesFromJSON,
    OrganizationRolesFromJSONTyped,
    OrganizationRolesToJSON,
    OrganizationRolesToJSONTyped,
} from './OrganizationRoles.js';
import type { TutteoProduct } from './TutteoProduct.js';
import {
    TutteoProductFromJSON,
    TutteoProductFromJSONTyped,
    TutteoProductToJSON,
    TutteoProductToJSONTyped,
} from './TutteoProduct.js';
import type { UserCommunityProfileLinks } from './UserCommunityProfileLinks.js';
import {
    UserCommunityProfileLinksFromJSON,
    UserCommunityProfileLinksFromJSONTyped,
    UserCommunityProfileLinksToJSON,
    UserCommunityProfileLinksToJSONTyped,
} from './UserCommunityProfileLinks.js';
import type { ClassRoles } from './ClassRoles.js';
import {
    ClassRolesFromJSON,
    ClassRolesFromJSONTyped,
    ClassRolesToJSON,
    ClassRolesToJSONTyped,
} from './ClassRoles.js';

/**
 * Public User details
 * @export
 * @interface UserPublic
 */
export interface UserPublic {
    /**
     * The user unique identifier
     * @type {string}
     * @memberof UserPublic
     */
    id: string;
    /**
     * The type of user account
     * @type {UserPublicTypeEnum}
     * @memberof UserPublic
     */
    type: UserPublicTypeEnum;
    /**
     * 
     * @type {TutteoProduct}
     * @memberof UserPublic
     */
    product: TutteoProduct;
    /**
     * The user name (unique for the organization)
     * @type {string}
     * @memberof UserPublic
     */
    username: string;
    /**
     * The name that can be directly printed (name, firstname & lastname, or username)
     * @type {string}
     * @memberof UserPublic
     */
    printableName?: string;
    /**
     * Firstname of the user (for education users)
     * @type {string}
     * @memberof UserPublic
     */
    firstname?: string;
    /**
     * Lastname of the user (for education users)
     * @type {string}
     * @memberof UserPublic
     */
    lastname?: string;
    /**
     * A displayable name for the user (for consumer users)
     * @type {string}
     * @memberof UserPublic
     */
    name?: string;
    /**
     * The URL of the picture to display
     * @type {string}
     * @memberof UserPublic
     */
    picture: string;
    /**
     * List of badges for the user profile:
     * 
     * - `power`
     * - `staff`
     * - `composerOfTheMonth`
     * - `ambassador`
     * - `challenge`
     * 
     * @type {Array<string>}
     * @memberof UserPublic
     */
    badges?: Array<string>;
    /**
     * Organization ID (for Edu users only)
     * @type {string}
     * @memberof UserPublic
     */
    organization?: string;
    /**
     * 
     * @type {OrganizationRoles}
     * @memberof UserPublic
     */
    organizationRole?: OrganizationRoles;
    /**
     * 
     * @type {ClassRoles}
     * @memberof UserPublic
     */
    classRole?: ClassRoles;
    /**
     * Link to user profile (for Indiv. users only)
     * @type {string}
     * @memberof UserPublic
     */
    htmlUrl?: string;
    /**
     * User's biography
     * @type {string}
     * @memberof UserPublic
     */
    bio?: string;
    /**
     * Date the user signed up
     * @type {Date}
     * @memberof UserPublic
     */
    registrationDate?: Date;
    /**
     * Number of the scores liked by the user
     * @type {number}
     * @memberof UserPublic
     */
    likedScoresCount?: number;
    /**
     * Number of followers the user have
     * @type {number}
     * @memberof UserPublic
     */
    followersCount?: number;
    /**
     * Number of people the user follow
     * @type {number}
     * @memberof UserPublic
     */
    followingCount?: number;
    /**
     * Number of public scores the user have
     * @type {number}
     * @memberof UserPublic
     */
    ownedPublicScoresCount?: number;
    /**
     * Total number of public scores the user participates in (owned + joined)
     * @type {number}
     * @memberof UserPublic
     */
    allPublicScoresCount?: number;
    /**
     * Number of likes on the user published scores
     * @type {number}
     * @memberof UserPublic
     */
    likesCount?: number;
    /**
     * Number of plays on the user published scores
     * @type {number}
     * @memberof UserPublic
     */
    playsCount?: number;
    /**
     * Cover picture (backgroud) for the profile
     * @type {string}
     * @memberof UserPublic
     */
    coverPicture?: string | null;
    /**
     * Theme (background) for the profile
     * @type {string}
     * @memberof UserPublic
     */
    profileTheme?: string;
    /**
     * 
     * @type {UserCommunityProfileLinks}
     * @memberof UserPublic
     */
    links?: UserCommunityProfileLinks;
}


/**
 * @export
 */
export const UserPublicTypeEnum = {
    User: 'user',
    Guest: 'guest'
} as const;
export type UserPublicTypeEnum = typeof UserPublicTypeEnum[keyof typeof UserPublicTypeEnum];


/**
 * Check if a given object implements the UserPublic interface.
 */
export function instanceOfUserPublic(value: object): value is UserPublic {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('product' in value) || value['product'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('picture' in value) || value['picture'] === undefined) return false;
    return true;
}

export function UserPublicFromJSON(json: any): UserPublic {
    return UserPublicFromJSONTyped(json, false);
}

export function UserPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'product': TutteoProductFromJSON(json['product']),
        'username': json['username'],
        'printableName': json['printableName'] == null ? undefined : json['printableName'],
        'firstname': json['firstname'] == null ? undefined : json['firstname'],
        'lastname': json['lastname'] == null ? undefined : json['lastname'],
        'name': json['name'] == null ? undefined : json['name'],
        'picture': json['picture'],
        'badges': json['badges'] == null ? undefined : json['badges'],
        'organization': json['organization'] == null ? undefined : json['organization'],
        'organizationRole': json['organizationRole'] == null ? undefined : OrganizationRolesFromJSON(json['organizationRole']),
        'classRole': json['classRole'] == null ? undefined : ClassRolesFromJSON(json['classRole']),
        'htmlUrl': json['htmlUrl'] == null ? undefined : json['htmlUrl'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'registrationDate': json['registrationDate'] == null ? undefined : (new Date(json['registrationDate'])),
        'likedScoresCount': json['likedScoresCount'] == null ? undefined : json['likedScoresCount'],
        'followersCount': json['followersCount'] == null ? undefined : json['followersCount'],
        'followingCount': json['followingCount'] == null ? undefined : json['followingCount'],
        'ownedPublicScoresCount': json['ownedPublicScoresCount'] == null ? undefined : json['ownedPublicScoresCount'],
        'allPublicScoresCount': json['allPublicScoresCount'] == null ? undefined : json['allPublicScoresCount'],
        'likesCount': json['likesCount'] == null ? undefined : json['likesCount'],
        'playsCount': json['playsCount'] == null ? undefined : json['playsCount'],
        'coverPicture': json['coverPicture'] === undefined ? undefined : json['coverPicture'] === null ? null : json['coverPicture'],
        'profileTheme': json['profileTheme'] == null ? undefined : json['profileTheme'],
        'links': json['links'] == null ? undefined : UserCommunityProfileLinksFromJSON(json['links']),
    };
}

export function UserPublicToJSON(json: any): UserPublic {
    return UserPublicToJSONTyped(json, false);
}

export function UserPublicToJSONTyped(value?: UserPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'product': TutteoProductToJSON(value['product']),
        'username': value['username'],
        'printableName': value['printableName'],
        'firstname': value['firstname'],
        'lastname': value['lastname'],
        'name': value['name'],
        'picture': value['picture'],
        'badges': value['badges'],
        'organization': value['organization'],
        'organizationRole': OrganizationRolesToJSON(value['organizationRole']),
        'classRole': ClassRolesToJSON(value['classRole']),
        'htmlUrl': value['htmlUrl'],
        'bio': value['bio'],
        'registrationDate': value['registrationDate'] == null ? value['registrationDate'] : value['registrationDate'].toISOString(),
        'likedScoresCount': value['likedScoresCount'],
        'followersCount': value['followersCount'],
        'followingCount': value['followingCount'],
        'ownedPublicScoresCount': value['ownedPublicScoresCount'],
        'allPublicScoresCount': value['allPublicScoresCount'],
        'likesCount': value['likesCount'],
        'playsCount': value['playsCount'],
        'coverPicture': value['coverPicture'],
        'profileTheme': value['profileTheme'],
        'links': UserCommunityProfileLinksToJSON(value['links']),
    };
}

